### ISSUE TITLE
A naive issue about starting MZmine2 (help needed!!)

### ISSUE THREAD

**Issue by xiaobolistanford** [mzmine/mzmine2#224]
I downloaded the MZmine-2.20.zip file onto my computer and clicked "startMZmine_MacOSX.command" to open the software but it didn't work.
I know very little about computer science and hope to get detailed instructions on how to fix it. Thanks very much!

My MZmine version: 2.20
My OS version: OS X Yosemite 10.10.2
Below is what I got:
“Java maximum heap size set to 6144 MB
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/mzmine/main/MZmineCore : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout

[Process completed]”

**Comment by tomas-pluskal** [comment]
MZmine requires Java 7 or newer. Your java is version 1.6.0_65 (see above). 
It is also possible that you have multiple versions of Java on your system. I recommend to download and install the latest JDK (not JRE) here: http://www.oracle.com/technetwork/java/javase/downloads/index.html
That should solve your issue.

**Comment by xiaobolistanford** [comment]
Thanks, tomas-pluskal! It's solved.
