### ISSUE TITLE
Bad link to YMDB search

### ISSUE THREAD

**Issue by mabawsa** [mzmine/mzmine2#248]
~/MZmine-2.20 $ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
~/MZmine-2.20 $ R --version
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

ISSUE:
Get the following error whilst trying to search the yeast metabolite database:
[14:07:50|FINEST|TaskQueue]: Adding task "Peak identification of 134.0177 using Yeast Metabolome Database (YMDB)" to the task controller queue
[14:07:50|INFO|WorkerThread]: Starting processing of task Peak identification of 134.0177 using Yeast Metabolome Database (YMDB)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://www.ymdb.ca/structures/structures/compounds/YMDB00280.sdf
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at net.sf.mzmine.util.InetUtils.retrieveData(InetUtils.java:42)
	at net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.databases.YMDBGateway.getCompound(YMDBGateway.java:90)
	at net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.SingleRowIdentificationTask.run(SingleRowIdentificationTask.java:160)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[14:07:52|WARNING|SingleRowIdentificationTask]: Could not connect to Yeast Metabolome Database (YMDB)(java.io.IOException: Server returned HTTP response code: 500 for URL: http://www.ymdb.ca/structures/structures/compounds/YMDB00280.sdf@sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840))
[14:07:52|SEVERE|WorkerThread]: Error of task Peak identification of 134.0177 using Yeast Metabolome Database (YMDB): Could not connect to Yeast Metabolome Database (YMDB): java.io.IOException: Server returned HTTP response code: 500 for URL: http://www.ymdb.ca/structures/structures/compounds/YMDB00280.sdf (HttpURLConnection.java:1840)

used the parameters for fumarate.
![parameters](https://cloud.githubusercontent.com/assets/7529270/16031711/4d2311da-3239-11e6-88bb-7e1fd41c9f61.png)

Yours,

Dougie

**Comment by mabawsa** [comment]
Probably linked to the recent changes in the HMDB searches.

**Comment by tomas-pluskal** [comment]
Try going to YMDB (e.g., http://www.ymdb.ca/compounds/YMDB00286) and clicking on the "SDF" link. It gives an error. So perhaps this should be reported to YMDB admins, instead of here.

**Comment by mabawsa** [comment]
Thanks, i have reported the error to YMDB.
