### ISSUE TITLE
error when importing raw data files

### ISSUE THREAD

**Issue by 1234new** [mzmine/mzmine2#249]
Mzmine 2.0

64bit

The directory name is invalid.
Error occurred while processing: 4ldt:~4.
The directory name is invalid.
Error occurred while processing: 2ldt:~6.
The directory name is invalid.
Error occurred while processing: 2ldt:~8.
The directory name is invalid.
Error occurred while processing: 2ldt:~10.
The directory name is invalid.
Error occurred while processing: 2ldt:~12.
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

![image](https://cloud.githubusercontent.com/assets/20042024/16190726/a55afb94-36d8-11e6-8483-f89690c0f531.png)

[11:18:32|WARNING|MzMLElement]: MzIdentML Configuration file: jar:file:/C:/Users
/dominion/Desktop/MZmine-2.20/lib/jmzml-1.7.4.jar!/defaultMzMLElement.cfg.xml
java.io.IOException: The filename, directory name, or volume label syntax is inc
orrect
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(Unknown Source)
        at java.io.File.createTempFile(Unknown Source)
        at net.sf.mzmine.project.impl.RawDataFileImpl.createNewDataPointsFile(Ra
wDataFileImpl.java:105)
        at net.sf.mzmine.project.impl.RawDataFileImpl.storeDataPoints(RawDataFil
eImpl.java:313)
        at net.sf.mzmine.project.impl.RawDataFileImpl.addScan(RawDataFileImpl.ja
va:403)
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLRe
adTask.run(MzMLReadTask.java:165)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)

[11:18:37|SEVERE|WorkerThread]: Error of task Opening file C:\datatosplit\conver
ted\negmzxmlfiles\NW1.mzML: Error parsing mzML: java.io.IOException: The filenam
e, directory name, or volume label syntax is incorrect (null:-2)

I cannot seem to import my data files to mzmine. The above error message appears each time. Could you please help?

Thanks

**Comment by tomas-pluskal** [comment]
MZmine needs to create temporary files for its data. It seems this fails on your system. Check the setting of the %TEMP% Windows environment variable, it might be pointing to some weird place. Alternatively, edit the startMZmine.bat script in a text editor and change this line:
```
set TMP_FILE_DIRECTORY=%TEMP%
```
to a temporary folder of your choice.

**Comment by 1234new** [comment]
Thanksyou for your message! I have checked and the temp file seems okay - i tried changing it to a folder of my choice but the same error message appears. 

The directory name is invalid.
Error occurred while processing: 4ldt:~4.
The directory name is invalid.
Error occurred while processing: 2ldt:~6.
The directory name is invalid.
Error occurred while processing: 2ldt:~8.
The directory name is invalid.
Error occurred while processing: 2ldt:~10.
The directory name is invalid.
Error occurred while processing: 2ldt:~12.
A subdirectory or file 6 already exists.
Error occurred while processing: 6.
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)


Any other ideas how to fix it?

**Comment by tomas-pluskal** [comment]
Can you try opening the same files in MZmine on another computer?

By the way, if you are really using MZmine version 2.0, please try with the latest version.

**Comment by picom** [comment]
I have the same error on my asus laptop with 6Gb, Windows 10 pro 64 on intel i7 processor, MZmine version 2.26. I tried it before with java x32, with same outcome.

I am surprised since it worked out of the box importing the same datasets on the first PC in the lab I tried it out. The PC has 64bit windows 10 and an older java32 VM.
I have already tried:
* disabling the antivirus
* using different file names/and or extensions and different drives
* changed the temporary directory
* closing the browser to free memory
These are the snippets from the system windows, sorry for the translated system errors, hope they are clear:
---
Checking physical memory size...
Found 6048 MB memory, 64-bit system
Java version is 1.8.0_131 (64-Bit)
Java maximum heap size set to 4000 MB
---
---
[11:55:29|FINEST|MainMenu]: Starting module Raw data import with parameters Raw data file names: [C:\Users\paridep\Desktop\prova.cdf]
[11:55:29|FINEST|RawDataImportModule]: File C:\Users\paridep\Desktop\prova.cdf type detected as NETCDF
[11:55:29|FINEST|TaskQueue]: Adding task "Opening file C:\Users\paridep\Desktop\prova.cdf" to the task controller queue
[11:55:29|INFO|WorkerThread]: Starting processing of task Opening file C:\Users\paridep\Desktop\prova.cdf
[11:55:30|INFO|NetCDFReadTask]: Started parsing file C:\Users\paridep\Desktop\prova.cdf
[11:55:30|SEVERE|NetCDFReadTask]: Could not open file C:\Users\paridep\Desktop\prova.cdf(java.io.IOException: La sintassi del nome del file, della directory o del volume non Þ corretta@java.io.WinNTFileSystem.createFileExclusively(Native Method))
[11:55:30|SEVERE|WorkerThread]: Error of task Opening file C:\Users\paridep\Desktop\prova.cdf: java.io.IOException: La sintassi del nome del file, della directory o del volume non Þ corretta (null:-2)
----

**Comment by tomas-pluskal** [comment]
The problem occurs in the code that creates temporary files. How **exactly** did you change the temporary directory?

**Comment by picom** [comment]
I run it first with %temp%, then with two other dirs on different disk,
coded in the batch file. The error is the same in all three cases.

Il 29/mag/2017 04:10 PM, "Tomáš Pluskal" <notifications@github.com> ha
scritto:

**Comment by tomas-pluskal** [comment]
Can you send a copy of the startMZmine script that you are using?

**Comment by picom** [comment]
My first try was with the out of the box .bat from the distribution, then I changed the temp directory, twice on different disks C: and D:. This file is the last attempt in the D disk. 
The programs manages to create a MZmine~0 directory in my temp directory.
[startMZmine_Windows.zip](https://github.com/mzmine/mzmine2/files/1038577/startMZmine_Windows.zip)

**Comment by tomas-pluskal** [comment]
There is a section in the bat file called "Make a unique temp folder for the MZmine instance"
I think the problem might be in there.

Maybe you can try changing this code:
````
set TMP_FILE_DIRECTORY=%TMP_FILE_DIRECTORY%\\%MZMINE_UNID%
mkdir %TMP_FILE_DIRECTORY%
````
to 
````
set TMP_FILE_DIRECTORY=D:\temp
````
Let me know if that worked

**Comment by picom** [comment]
Yes, it does. Hope this will be useful for next release. Many thanks.
![image](https://cloud.githubusercontent.com/assets/13470072/26588926/f716b6ca-4556-11e7-81dc-fbbe7c1dd2e6.png)

**Comment by tomas-pluskal** [comment]
Thanks, I fixed this for the next release

**Comment by tczauderna** [comment]
I think this issue should be opened again because the fix causes other problems.

**On Windows**
The batch script uses `%TEMP%` on Windows to get the default temp folder and stores it in `TMP_FILE_DIRECTORY`.
`TMP_FILE_DIRECTORY` most likely points to `C:\Users\username\AppData\Local\Temp\` then.
The last line of the script is `RD /S /Q %TMP_FILE_DIRECTORY%` which means the batch script tries to delete the default temp folder without user confirmation. Since this folder most likely contains locked files this fails and doesn't cause any further problems except that MZmine's temp files don't get deleted.

**On Windows Server with Remote Desktop**
The batch script uses `%TEMP%` on Windows Server to get the default temp folder and stores it in `TMP_FILE_DIRECTORY`.
With a remote desktop session `TMP_FILE_DIRECTORY` most likely points to `C:\Users\username\AppData\Local\Temp\###` then with `###` being a session ID (see here [https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc755098(v=ws.11)](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc755098(v=ws.11)))
The last line of the script is `RD /S /Q %TMP_FILE_DIRECTORY%` which means the batch script tries to delete the default temp folder without user confirmation. This folder most likely doesn't contain any locked files and the default temp folder gets deleted.
Since %TEMP% points to that folder MZmine and other software might have problems finding the temp folder.
Running MZmine (2.32) again we get an exception
`java.io.IOException: The system cannot find the path specified`
`at java.io.WinNTFileSystem.createFileExclusively(Native Method)`
`at java.io.File.createTempFile(Unknown Source)`
`at java.io.File.createTempFile(Unknown Source)`
`at net.sf.mzmine.project.impl.RawDataFileImpl.createNewDataPointsFile(RawDataFileImpl.java:111)`
`at net.sf.mzmine.project.impl.RawDataFileImpl.storeDataPoints(RawDataFileImpl.java:323)`
`at net.sf.mzmine.project.impl.RawDataFileImpl.addScan(RawDataFileImpl.java:413)`
MZmine cannot create temp files because the default temp folder doesn't exist anymore since it has been deleted in the previous run.

**Comment by tomas-pluskal** [comment]
@tczauderna Thanks for letting us know. I'll look into it.
