### ISSUE TITLE
MZmine unable to start (in my computer)

### ISSUE THREAD

**Issue by KaiPongLaw** [mzmine/mzmine2#376]
Windows 10 home 64bit
MZmine ver. 2.29
Java ver. 8 update 151 (build 1.8.0_151-b12)
R 3.4.2 (official version and Microsoft version installed)

click on the bat file and it goes as much as the log below shows, what wrong?
========

Checking physical memory size...
Found 7988 MB memory, 64-bit system
Java version is 1.8.0_151 (64-Bit)
Java maximum heap size set to 5940 MB

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

[7:35:39|INFO|MZmineCore]: Starting MZmine 2.29
[7:35:40|FINE|TmpFileCleanup]: Checking for old temporary files...
[7:35:40|FINE|MZmineCore]: Loading core classes..
[7:35:40|FINE|MZmineCore]: Initializing core classes..
[7:35:40|FINE|MZmineCore]: Loading modules
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectload.ProjectLoadModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveAsModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectclose.ProjectCloseModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.batchmode.BatchModeModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.rawdataexport.RawDataExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.shoulderpeaksfilter.ShoulderPeaksFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.ChromatogramBuilderModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChromatogramBuilderModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.adap3d.ADAP3DModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.gridmass.GridMassModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.manual.ManualPeakPickerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.msms.MsMsPeakPickerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scanfilters.ScanFiltersModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.cropper.CropFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.baselinecorrection.BaselineCorrectionModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.alignscans.AlignScansModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scansmoothing.ScanSmoothingModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.orderdatafiles.OrderDataFilesModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.orderpeaklists.OrderPeakListsModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.join.JoinAlignerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.ransac.RansacAlignerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.csvexport.CSVExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.metaboanalystexport.MetaboAnalystExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabexport.MzTabExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.sqlexport.SQLExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlexport.XMLExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.casmiimport.CasmiImportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabimport.MzTabImportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlimport.XMLImportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mspexport.MSPExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mgfexport.MGFExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.gnpsexport.GNPSExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.siriusexport.SiriusExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.samerange.SameRangeGapFillerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.deisotoper.IsotopeGrouperModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.isotopeprediction.IsotopePatternCalculator
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.smoothing.SmoothingModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.shapemodeler.ShapeModelerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.peakextender.PeakExtenderModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.adap3decompositionV1_5.ADAP3DecompositionV1_5Module
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.adap3decompositionV2.ADAP3DecompositionV2Module
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.duplicatefilter.DuplicateFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.rowsfilter.RowsFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.peakcomparisonrowfilter.PeakComparisonRowFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.peakfilter.PeakFilterModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.clearannotations.PeaklistClearAnnotationsModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.rtnormalizer.RTNormalizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.linear.LinearNormalizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.standardcompound.StandardCompoundNormalizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.cvplot.CVPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.logratioplot.LogratioPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.PCAPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.CDAPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.SammonsPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.clustering.ClusteringModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.heatmaps.HeatMapModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.customdbsearch.CustomDBSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulaprediction.FormulaPredictionModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.fragmentsearch.FragmentSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.adductsearch.AdductSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.complexsearch.ComplexSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.OnlineDBSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.glycerophospholipidsearch.GPLipidSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.camera.CameraSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.nist.NistMsSearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulapredictionpeaklist.FormulaPredictionPeakListModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.ms2search.Ms2SearchModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.tic.TICVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.SpectraVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.twod.TwoDVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.threed.ThreeDVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.msms.MsMsVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.neutralloss.NeutralLossVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.PeakListTableModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.IsotopePatternExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.MSMSExportModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.scatterplot.ScatterPlotVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.histogram.HistogramVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.infovisualizer.InfoVisualizerModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.intensityplot.IntensityPlotModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrangecalculator.MzRangeMassCalculatorModule
[7:35:40|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrangecalculator.MzRangeFormulaCalculatorModule
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
        at java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
        at java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
        at net.sf.mzmine.main.MZmineCore.main(MZmineCore.java:182)

**Comment by tomas-pluskal** [comment]
Have you tried Googling?
E.g., https://stackoverflow.com/questions/15260989/exception-in-thread-main-java-awt-awterror-assistive-technology-not-found
In any case, this does not seem to be a problem of MZmine.

**Comment by KaiPongLaw** [comment]
thank for the suggestion. It is Java problem, not MZmine.  

the suggested solution at stackoverflow is not appropriate. the links there leads to a very old (2011) version of Java Access Bridge. there is of course no new version either elsewhere. 

Java Access Bridge should be installed properly with jre ver. 7, 8 or 9. what has gone wrong and how to fix it?

**Comment by tomas-pluskal** [comment]
I have no idea, never seen this before. Try googling some more.
