### ISSUE TITLE
Cannot open Thermo raw files

### ISSUE THREAD

**Issue by Giantlanb** [mzmine/mzmine2#402]
Hi,
MZmine ver 2.3
OS : 64 bit

Output:

        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.readRAWDump(NativeFileReadTask.java:206)
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.run(NativeFileReadTask.java:139)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[16:36:02|SEVERE|WorkerThread]: Error of task Opening file C:\Desktop\Integration_Test.raw: java.io.IOException: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component wi (NativeFileReadTask.java:206)032-DC70ACDBDC02} failed due to the following error: 800736b1.

For some reason it doesn't allow me to add images but the error message is the same as the one reported in the console window. 

Please help.

Thanks

**Comment by photocyte** [comment]
Hi there,

What OS are you using?  64-bit is a bit ambiguous.  E.g. Linux, Mac, Linux?  The method of Thermo raw file reading differs depending on the OS.  

In the meantime, I'd recommend using the ProteoWizard MSConvert application (http://proteowizard.sourceforge.net/downloads.shtml), to convert your .raw file to .mzML and try loading the .mzML file.

**Comment by Giantlanb** [comment]
Sorry about that. I am using Windows 10 64bit version. I am installing MS Convert for now.

**Comment by tomas-pluskal** [comment]
You can also try installing MSFileReader from Thermo. That might solve the import issue in MZmine, because it will install all the required libraries. You can grab it here: https://github.com/frallain/MSFileReader-Python-bindings/tree/master/MSFileReader

**Comment by Giantlanb** [comment]
I installed MSFileReader from Thermo, it works great now. 
Thank you.
