### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by schii513** [mzmine/mzmine2#419]
Hi. I'm a student using MZmine2 to process MSMS data.
When I deconvolute my data through XCMS Rerve this error massage appear.
How can I solve this problem?

[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.begin(Rsession.java:657)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.startup(Rsession.java:562)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.<init>(Rsession.java:504)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.<init>(Rsession.java:512)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.newInstanceTry(Rsession.java:473)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.getRengineInstance(RSessionWrapper.java:341)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.open(RSessionWrapper.java:1105)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.run(DeconvolutionTask.java:142)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[11:04:37|FINEST|RSessionWrapper]: net.sf.mzmine.util.R.RSessionWrapperException: Could not start Rserve ( R> install.packages(c('Rserve')) ). Please check if R and Rserve are installed and, in case the path to the R installation directory could not be detected automatically, if the 'R executable path' is properly set in the project's preferences. (Note: alternatively, the 'R_HOME' environment variable can also be used).
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.getRengineInstance(RSessionWrapper.java:370)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.open(RSessionWrapper.java:1105)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.run(DeconvolutionTask.java:142)
[11:04:37|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[11:04:37|SEVERE|WorkerThread]: Error of task Peak recognition on 180208_3.mzXML filtered chromatograms: 'R computing error' during CentWave detection.
Could not start Rserve ( R> install.packages(c('Rserve')) ). Please check if R
and Rserve are installed and, in case the path to the R installation directory
could not be detected automatically, if the 'R executable path' is properly set
in the project's preferences. (Note: alternatively, the 'R_HOME' environment
variable can also be used).

**Comment by mlovas** [comment]
I have the same problem after i update my R from 3.4.1 to 3.4.3. All of the required packages has been installed, the path is correct, but mzmine could not start R. Btw, it still works with the older 3.4.1 R version.

**Comment by schii513** [comment]
@mlovas Thank you so much!! Your solution work :D
