### ISSUE TITLE
Heat Map not working

### ISSUE THREAD

**Issue by CarolinaVictal** [mzmine/mzmine2#438]
### Setup

I am reporting a problem with MZmine 2 version 2.32 
My operating system is Windows 10, 64-bit

When I try to run the Heat Map in an aligned peak list, it starts processing but stops at 80%. There is no apparent error: in the "task in process" box it is said to be processing; in the bar below the last message is "Heat Map Plot" and in the console window says that:

[15:40:03|FINEST|MainMenu]: Setting parameters for module Heat map plot
[15:40:12|FINEST|MainMenu]: Starting module Heat map plot with parameters Peak lists: Aligned peak list, Output name: C:\Users\Antonio\Desktop\FAE\HeatMatFAE, Output file type: pdf, Sample parameter: Group, Group of reference: Xil, Only identified rows: false, Use peak area: true, Scaling: true, Log: true, Show control samples: true, P-value legend: true, Size p-value legend: 5, Height: 10, Width: 10, Column margin: 10, Row margin: 10, R engine: RCaller
[15:40:12|FINEST|TaskQueue]: Adding task "Heat map... " to the task controller queue
[15:40:12|INFO|WorkerThread]: Starting processing of task Heat map...
[15:40:12|INFO|HeatMapTask]: Heat map plot
[15:40:15|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[15:40:15|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[15:40:15|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[15:40:15|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[15:40:15|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[15:40:15|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[15:40:20|FINEST|RSessionWrapper]: R version 3.5.0 (2018-04-23)

I can't find where the error is. The java installed is jre 1.8.0 and R is 3.5.0 (64-bit). 
ps: I am using the RCaller in the parameters.

When I try the RServer, the problem is even bigger. In the "task in process" box is the same as the other, but in the  window that is what happens:
[16:28:58|FINEST|MainMenu]: Setting parameters for module Heat map plot
[16:29:02|FINEST|MainMenu]: Starting module Heat map plot with parameters Peak lists: Aligned peak list, Output name: C:\Users\Antonio\Desktop\FAE\HeatMatFAE, Output file type: pdf, Sample parameter: Group, Group of reference: Xil, Only identified rows: false, Use peak area: true, Scaling: true, Log: true, Show control samples: true, P-value legend: true, Size p-value legend: 5, Height: 10, Width: 10, Column margin: 10, Row margin: 10, R engine: RServe
[16:29:02|FINEST|TaskQueue]: Adding task "Heat map... " to the task controller queue
[16:29:03|INFO|WorkerThread]: Starting processing of task Heat map...
[16:29:03|INFO|HeatMapTask]: Heat map plot
[16:29:05|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[16:29:06|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[16:29:06|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[16:29:07|FINEST|RSessionWrapper]:   failed: timed out
[16:29:07|FINEST|RSessionWrapper]: Connection R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6311 failed.
[16:29:07|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6311 is not accessible.
 ! null
[16:29:07|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6311
[16:29:07|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[16:29:07|FINEST|RSessionWrapper]: Failed to connect: Cannot connect: Connection refused: connect
[16:29:07|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[16:29:07|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[16:29:07|FINEST|RSessionWrapper]: checking Rserve is available...
[16:29:13|FINEST|RSessionWrapper]:   executing "C:\Program Files\R\R-3.5.0\bin\R.exe" -e "i=installed.packages();is.element(set=i,el='Rserve')" --vanilla -q
[16:29:21|FINEST|RSessionWrapper]:   ok
[16:29:21|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6311
[16:29:21|FINEST|RSessionWrapper]: Waiting for Rserve to start ...
[16:29:21|FINEST|RSessionWrapper]:   executing "C:\Program Files\R\R-3.5.0\bin\R.exe" -e "library(Rserve);Rserve(FALSE,args='--no-save --slave  --RS-pidfile "C:/Users/Antonio/AppData/Local/Temp/rs_pid_63114681514692135730108.pid" --RS-port 6311')" --no-save --slave
[16:29:21|FINEST|RSessionWrapper]: Rserve startup done, let us try to connect ...
[16:29:22|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:29:24|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:29:25|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:29:27|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:29:28|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:29:29|FINEST|RSessionWrapper]: !!   failed
 ! null
[16:29:31|FINEST|RSessionWrapper]:   failed: timed out
[16:29:31|FINEST|RSessionWrapper]: Connection R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6311 failed.
[16:29:31|FINEST|RSessionWrapper]: !! Failed to launch local Rserve. Unable to initialize Rsession.
 ! null
[16:29:31|FINEST|RSessionWrapper]: Failed to launch local Rserve. Unable to initialize Rsession.
[16:29:31|FINEST|RSessionWrapper]: Failed to connect: Cannot connect: Connection refused: connect
[16:29:31|FINEST|RSessionWrapper]: java.lang.IllegalArgumentException: Failed to launch local Rserve. Unable to initialize Rsession.
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.begin(Rsession.java:657)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.startup(Rsession.java:562)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.<init>(Rsession.java:504)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.<init>(Rsession.java:512)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.newInstanceTry(Rsession.java:473)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.getRengineInstance(RSessionWrapper.java:341)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.open(RSessionWrapper.java:1105)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.dataanalysis.heatmaps.HeatMapTask.run(HeatMapTask.java:157)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[16:29:31|FINEST|RSessionWrapper]: net.sf.mzmine.util.R.RSessionWrapperException: Could not start Rserve ( R> install.packages(c('Rserve')) ). Please check if R and Rserve are installed and, in case the path to the R installation directory could not be detected automatically, if the 'R executable path' is properly set in the project's preferences. (Note: alternatively, the 'R_HOME' environment variable can also be used).
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.getRengineInstance(RSessionWrapper.java:370)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.open(RSessionWrapper.java:1105)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.dataanalysis.heatmaps.HeatMapTask.run(HeatMapTask.java:157)
[16:29:31|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
[16:29:31|SEVERE|WorkerThread]: Error of task Heat map... : 'R computing error' during heatmap generation.
Could not start Rserve ( R> install.packages(c('Rserve')) ). Please check if R
and Rserve are installed and, in case the path to the R installation directory
could not be detected automatically, if the 'R executable path' is properly set
in the project's preferences. (Note: alternatively, the 'R_HOME' environment
variable can also be used).
[16:29:57|FINEST|MainMenu]: Setting parameters for module Heat map plot
[16:30:31|FINEST|MainMenu]: Setting parameters for module Heat map plot
[16:30:34|FINEST|MainMenu]: Starting module Heat map plot with parameters Peak lists: Aligned peak list, Output name: C:\Users\Antonio\Desktop\FAE\HeatMatFAE, Output file type: pdf, Sample parameter: Group, Group of reference: Xil, Only identified rows: false, Use peak area: true, Scaling: true, Log: true, Show control samples: true, P-value legend: true, Size p-value legend: 5, Height: 10, Width: 10, Column margin: 10, Row margin: 10, R engine: RServe
[16:30:34|FINEST|TaskQueue]: Adding task "Heat map... " to the task controller queue
[16:30:34|INFO|WorkerThread]: Starting processing of task Heat map...
[16:30:34|INFO|HeatMapTask]: Heat map plot
[16:30:36|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[16:30:36|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[16:30:36|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[16:30:37|FINEST|RSessionWrapper]:   failed: timed out
[16:30:37|FINEST|RSessionWrapper]: Connection R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6312 failed.
[16:30:37|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6312 is not accessible.
 ! null
[16:30:37|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6312
[16:30:37|FINEST|RSessionWrapper]: Failed to connect: Cannot connect: Connection refused: connect
[16:30:37|FINEST|RLocationDetection]: Windows: Query registry to find where R is installed ...
[16:30:38|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.5.0
[16:30:38|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\Program Files\R\R-3.5.0\bin\R.exe'
[16:30:38|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:3be81953-0b2e-4334-adcd-ad5ec870769d@localhost:6312
[16:30:38|FINEST|RSessionWrapper]: Waiting for Rserve to start ...
[16:30:38|FINEST|RSessionWrapper]:   executing "C:\Program Files\R\R-3.5.0\bin\R.exe" -e "library(Rserve);Rserve(FALSE,args='--no-save --slave  --RS-pidfile "C:/Users/Antonio/AppData/Local/Temp/rs_pid_63128891950475896176093.pid" --RS-port 6312')" --no-save --slave
[16:30:38|FINEST|RSessionWrapper]: Rserve startup done, let us try to connect ...
[16:30:39|FINEST|RSessionWrapper]: Try failed with: Cannot connect: Connection refused: connect
[16:30:40|FINEST|RSessionWrapper]: Rserve is running.
[16:30:40|FINEST|RSessionWrapper]:   ok
[16:30:41|FINEST|RSessionWrapper]: Local Rserve started. (Version 103)
[16:30:41|FINEST|RSessionWrapper]: Rserve: started instance (pid: '3100' | port: '6312').
[16:30:41|FINEST|RSessionWrapper]: R version 3.5.0 (2018-04-23)
[16:30:41|FINEST|RSessionWrapper]: 103
[16:30:41|FINEST|RSessionWrapper]: UTF-8
[16:30:41|FINEST|RSessionWrapper]: Loading package 'gplots'...
[16:30:41|FINEST|RSessionWrapper]: Load status: 'true'.
[16:30:41|FINEST|RSessionWrapper]: Loaded package: 'gplots'.
[16:30:42|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:42|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:43|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:44|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:44|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:44|FINEST|RSessionWrapper]: !!     Repeated 44 times.
 R>
 R! eval failed, request status: error code: 127
[16:30:44|FINEST|RSessionWrapper]: !! [exception] eval failed, request status: error code: 127
  dataset[55,4] = NA
 R> [exception] eval failed, request status: error code: 127
  dataset[55,4] = NA
 R! eval failed, request status: error code: 127
[16:30:44|FINEST|RSessionWrapper]:     Repeated 100 times.
[16:30:45|FINEST|RSessionWrapper]:     Repeated 100 times.
.
.
.
From this point, it just repeats this message above (from the error code 127 to repeating 100 times....again and again)

I don't know what to do. Do I have to install R "inside" mzmine? What can I do??

**Comment by tomas-pluskal** [comment]
Have you installed the required R modules?

**Comment by CarolinaVictal** [comment]
Yes. I installed the modules described at the mzmine page. 
I don't really know how R works with mzmine. Should the R .exe be inside the mzmine file? That's my doubt. 
And it's a weird error, since it doesn't say that is a problem with R.

**Comment by georgiatr** [comment]
Can you tell me how you solved the problem with the heatmap in mzmine stuck in 80%? I am using the Rcaller also.

**Comment by typewritermonkey** [comment]
Did anyone figure this out yet
