### ISSUE TITLE
MzMine crashes in server

### ISSUE THREAD

**Issue by nareshibt** [mzmine/mzmine2#450]
### Setup
I tried running Mzmine - 2.3.3 in linux cluster it crashed with this error

Below I pasted the exact output of the following commands:
```
mkdir: cannot create directory ‘/scratchalpha/rambabu/data_analysis/software/MZmine-2.33/tmp/MZMINE388094’: No such file or directory
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxa6460sr16fp15-20151106_01(SR16 FP15))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr16fp15-20151020_272943 (JIT enabled, AOT enabled)
J9VM - 20151020_272943
JIT  - r9_20151019_103450
GC   - GA24_Java6_SR16_20151020_1627_B272943)
JCL  - 20151105_01

Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=net/sf/mzmine/main/MZmineCore, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:286)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:538)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$300(URLClassLoader.java:77)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1041)
	at java.security.AccessController.doPrivileged(AccessController.java:448)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:427)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:676)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:642)
Could not find the main class: net.sf.mzmine.main.MZmineCore.  Program will exit.```

**Comment by tomas-pluskal** [comment]
Recent MZmine versions require Java 8 or newer. You are using Java 6.

**Comment by tomas-pluskal** [comment]
There is no error in your log, so I would say your batch is processing ok. 
The warning message comes from the Java runtime, not from MZmine. I don't know what that means, try googling.

**Comment by dhxsy1994** [comment]
the jdk bugs appears on my 1024 processors machine

**Comment by tomas-pluskal** [comment]
Have you tried a newer JDK (version 12)?
