### ISSUE TITLE
Peak Deconvolution No Longer Working In Windows (XCMS)

### ISSUE THREAD

**Issue by JDDQ** [mzmine/mzmine2#484]
I am reporting a problem with MZmine 2 when using peak deconvolution (XCMS) on a windows 10. I have already installed all the dependencies and the problem doesn't seem to be reproducible on my Mac. When trying to use XCMS I receive errors regardless what R engine I use. Below I will add both of these outputs (Rcaller and Rserve). I should also say ADAP works, but XCMS gives a better fit of my data, which is why I would like to use it if possible. Also my Mac only has two cores, which is also why I am trying to do this on my windows.

Thanks for any assistance!!
  
My operating system is Windows 10 64-bit 
java -version 1.8  x86_64
R --version 3.5.1

Rserve
Error: R computing error during CentWave detection, Rserve connectivity failure

2:13:31|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:31|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:32|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:32|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:32|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:33|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:33|FINEST|CentWaveDetector]: Processing peak matrix...
[12:13:33|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:33|FINEST|CentWaveDetector]: Processing peak matrix...
[12:13:33|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:33|FINEST|CentWaveDetector]: Processing peak matrix...
[12:13:33|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:33|FINEST|RSessionWrapper]:     Repeated 100 times.
[12:13:33|FINEST|CentWaveDetector]: Processing peak matrix...
[12:13:33|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:33|FINEST|CentWaveDetector]: Processing peak matrix...
[12:13:33|FINEST|CentWaveDetector]: Detecting peaks.
[12:13:35|FINEST|RSessionWrapper]: java.net.SocketException: Connection reset
[12:13:35|FINEST|RSessionWrapper]:      at java.net.SocketInputStream.read(Unknown Source)
[12:13:35|FINEST|RSessionWrapper]:      at java.net.SocketInputStream.read(Unknown Source)
[12:13:35|FINEST|RSessionWrapper]:      at java.net.SocketInputStream.read(Unknown Source)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:213)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:258)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.Rserve.RConnection.parseAndEval(RConnection.java:497)
[12:13:35|FINEST|RSessionWrapper]:      at org.rosuda.REngine.REngine.parseAndEval(REngine.java:108)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.silentlyVoidEval(Rsession.java:1117)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.Rsession.Rsession.voidEval(Rsession.java:1166)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.eval(RSessionWrapper.java:788)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.eval(RSessionWrapper.java:754)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.centwave.CentWaveDetector.centWave(CentWaveDetector.java:215)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.centwave.CentWaveDetector.resolvePeaks(CentWaveDetector.java:126)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.resolvePeaks(DeconvolutionTask.java:258)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.run(DeconvolutionTask.java:141)
[12:13:35|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[12:13:35|FINEST|RSessionWrapper]: !!     Repeated 32 times.
 R>
 R! eval failed

Rcaller : Unhandled exception in task Peak recognition on mzdata.xml: java.lang.NullpointerException (RSessionErapper.java:1155)

[12:24:22|FINEST|MainMenu]: Starting module Chromatogram deconvolution with parameters Peak lists: 2p.mzdata.xml baseline-corrected chromatograms normalized, Suffix: deconvoluted, Algorithm: Wavelets (XCMS), m/z range for MS2 scan pairing (Da): false, RT range for MS2 scan pairing (min): false, Remove original peak list: false
[12:24:22|FINEST|TaskQueue]: Adding task "Peak recognition on 2p.mzdata.xml baseline-corrected chromatograms normalized" to the task controller queue
[12:24:22|INFO|WorkerThread]: Starting processing of task Peak recognition on 2p.mzdata.xml baseline-corrected chromatograms normalized
[12:24:22|INFO|DeconvolutionTask]: Started peak deconvolution on 2p.mzdata.xml baseline-corrected chromatograms normalized
[12:24:22|FINEST|RLocationDetection]: R path set to 'C:\Program Files\Microsoft\R Open\R-3.5.1\bin\x64\R.exe' based on MZmine preferences
[12:24:22|FINEST|RSessionWrapper]: java.lang.NoClassDefFoundError: Could not initialize class com.github.rcaller.util.Globals
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.getRengineInstance(RSessionWrapper.java:384)
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.open(RSessionWrapper.java:1072)
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.run(DeconvolutionTask.java:135)
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[12:24:22|SEVERE|WorkerThread]: Unhandled exception java.lang.NullPointerException while processing task Peak recognition on 2p.mzdata.xml baseline-corrected chromatograms normalized(java.lang.NullPointerException@net.sf.mzmine.util.R.RSessionWrapper.close(RSessionWrapper.java:1155))
[12:24:22|FINEST|RSessionWrapper]: java.lang.NullPointerException
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.util.R.RSessionWrapper.close(RSessionWrapper.java:1155)
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionTask.run(DeconvolutionTask.java:177)
[12:24:22|FINEST|RSessionWrapper]:      at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)

**Comment by metaboanna** [comment]
Hi, I have similar problem. If anybody contact you or answer? Or maybe now you have resolved the problem?

**Comment by JDDQ** [comment]
Hello,
	Sorry for the late response! No, I spoke to some of the people keeping MZmine functional and they have no intent to fix the XCMS as I was told “you can edit the Mzdata to regain XCMS functionality” Although I could never find what changes to the file are required…I suppose ADAP is the only working deconvolution using wavelets. If you ever discover a work around to XCMS let me know, but at this time I think you have to use an alternative to XCMS or use a mac for your deconvolution!

**Comment by JDDQ** [comment]
Hello, Sorry for the late response! No, XCMS was never updated, but I was told “you can edit the Mzdata to regain XCMS functionality” Although I could never find what changes to the file are required…I suppose ADAP is the only working deconvolution using wavelets. If you ever discover a work around to XCMS let me know, but at this time I think you have to use an alternative to XCMS or use a mac for your deconvolution!

**Comment by tomas-pluskal** [comment]
The truth is that the XCMS/R binding to MZmine was always a hackery that would break with each new XCMS version. There simply is noone willing to maintain the code.

**Comment by xiaodfeng** [comment]
I also come across the same problem.
