### ISSUE TITLE
MZmine stops while importing raw data

### ISSUE THREAD

**Issue by NewUser872** [mzmine/mzmine2#507]
### Setup

I am reporting a problem with MZmine 2 version 2.35
My operating system is Ubuntu 18.04.1 LTS, 64-bit.

Below I pasted the exact output of the following commands:
```
java -version
R --version

java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

```

### Expected behavior

Batch file runs to completion.

### Actual behavior

Batch stops during raw data import. I want to import ~2500 files. Here's the tail end of the terminal readout:
```

[14:46:23|INFO|WorkerThread]: Processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D6_20180719_1D6_v2.mzML done, status FINISHED
[14:46:23|FINEST|RawDataFileImpl]: Writing of scans to file /tmp/MZMINE21757/mzmine8169513238750800488.scans finished
[14:46:23|INFO|MzMLReadTask]: Finished parsing /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D1_20180719_1D1_v2.mzML, parsed 1547 scans
[14:46:23|INFO|WorkerThread]: Processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D1_20180719_1D1_v2.mzML done, status FINISHED
[14:46:23|FINEST|RawDataFileImpl]: Writing of scans to file /tmp/MZMINE21757/mzmine8828775390307939564.scans finished
[14:46:23|INFO|MzMLReadTask]: Finished parsing /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D1_20180719_1D1_v1.mzML, parsed 1547 scans
[14:46:23|INFO|WorkerThread]: Processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D1_20180719_1D1_v1.mzML done, status FINISHED
[14:46:23|INFO|WorkerThread]: Starting processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML
[14:46:23|INFO|MzMLReadTask]: Started parsing file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML
[14:46:23|INFO|WorkerThread]: Starting processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML
[14:46:23|INFO|MzMLReadTask]: Started parsing file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML
[14:46:23|INFO|WorkerThread]: Starting processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML
[14:46:23|INFO|MzMLReadTask]: Started parsing file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML
[14:46:23|SEVERE|MzMLIndexerFactory]: MzMLIndexerFactory$MzMlIndexerImpl.MzMlIndexerImpl(java.io.FileNotFoundException: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML (Too many open files)@java.io.FileInputStream.open0(Native Method))
[14:46:23|SEVERE|MzMLIndexerFactory]: MzMLIndexerFactory$MzMlIndexerImpl.MzMlIndexerImpl(java.io.FileNotFoundException: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML (Too many open files)@java.io.FileInputStream.open0(Native Method))
[14:46:23|SEVERE|MzMLIndexerFactory]: MzMLIndexerFactory$MzMlIndexerImpl.MzMlIndexerImpl(java.io.FileNotFoundException: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML (Too many open files)@java.io.FileInputStream.open0(Native Method))
[14:46:23|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML while processing task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML(java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML@uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113))
[14:46:23|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML while processing task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML(java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML@uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113))
[14:46:23|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML while processing task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML(java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML@uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113))
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[14:46:23|SEVERE|HeadLessDesktop]: Unhandled exception in task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML: java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v11.mzML (MzMLIndexerFactory.java:113)
[14:46:23|SEVERE|HeadLessDesktop]: Unhandled exception in task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML: java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v1.mzML (MzMLIndexerFactory.java:113)
[14:46:23|SEVERE|HeadLessDesktop]: Unhandled exception in task Opening file /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML: java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F21B_BQC_F11_2_20180730_v10.mzML (MzMLIndexerFactory.java:113)
[14:46:24|FINEST|RawDataFileImpl]: Writing of scans to file /tmp/MZMINE21757/mzmine2204308065508240667.scans finished
[14:46:24|INFO|MzMLReadTask]: Finished parsing /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D5_20180719_1D5_v2.mzML, parsed 1547 scans
[14:46:24|INFO|WorkerThread]: Processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D5_20180719_1D5_v2.mzML done, status FINISHED
[14:46:24|FINEST|RawDataFileImpl]: Writing of scans to file /tmp/MZMINE21757/mzmine1077747280900061572.scans finished
[14:46:24|INFO|MzMLReadTask]: Finished parsing /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D6_20180719_1D6_v3.mzML, parsed 1547 scans
[14:46:24|INFO|WorkerThread]: Processing of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_D6_20180719_1D6_v3.mzML done, status FINISHED
[14:46:24|SEVERE|MzMLIndexerFactory]: MzMLIndexerFactory$MzMlIndexerImpl.MzMlIndexerImpl(java.io.FileNotFoundException: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML (Too many open files)@java.io.FileInputStream.open0(Native Method))
[14:46:24|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML while processing task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML(java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML@uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113))
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[14:46:24|SEVERE|HeadLessDesktop]: Unhandled exception in task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML: java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v1.mzML (MzMLIndexerFactory.java:113)
java.io.IOException: Too many open files
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at net.sf.mzmine.project.impl.RawDataFileImpl.createNewDataPointsFile(RawDataFileImpl.java:107)
	at net.sf.mzmine.project.impl.RawDataFileImpl.storeDataPoints(RawDataFileImpl.java:312)
	at net.sf.mzmine.project.impl.RawDataFileImpl.addScan(RawDataFileImpl.java:402)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:156)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
java.io.IOException: Too many open files
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at net.sf.mzmine.project.impl.RawDataFileImpl.createNewDataPointsFile(RawDataFileImpl.java:107)
	at net.sf.mzmine.project.impl.RawDataFileImpl.storeDataPoints(RawDataFileImpl.java:312)
	at net.sf.mzmine.project.impl.RawDataFileImpl.addScan(RawDataFileImpl.java:402)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:156)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[14:46:24|SEVERE|WorkerThread]: Error of task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H4_20180719_1H4_v2.mzML: Error parsing mzML: java.io.IOException: Too many open files (UnixFileSystem.java:-2)
[14:46:24|SEVERE|HeadLessDesktop]: Error parsing mzML: java.io.IOException: Too many open files (UnixFileSystem.java:-2)
[14:46:24|SEVERE|MzMLIndexerFactory]: MzMLIndexerFactory$MzMlIndexerImpl.MzMlIndexerImpl(java.io.FileNotFoundException: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML (Too many open files)@java.io.FileInputStream.open0(Native Method))
[14:46:24|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML while processing task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML(java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML@uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113))
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[14:46:24|SEVERE|HeadLessDesktop]: Unhandled exception in task Opening file /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML: java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v2.mzML (MzMLIndexerFactory.java:113)
java.lang.IllegalStateException: Could not generate MzML index for file: /home/user/Documents/Converted_Data_Proteowizard/F20_SPE_SS2016043_H5_20180719_1H5_v3.mzML
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:113)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.MzMLReadTask.run(MzMLReadTask.java:104)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
```

### Steps to reproduce the problem

Create a batch file as follows:
1) Save project
2) Import ~2500 raw data files

This occurs on a server with 80 cores and over 300GB RAM. The maximum open file descriptors appears to be over 40 million:
```
$ cat /proc/sys/fs/file-max
41233227
```

**Comment by tomas-pluskal** [comment]
Well, there is a clear error message in your output: ```java.io.IOException: Too many open files```

You might be hitting some JVM limit or some security restriction on your platform. In any case, this is not really a problem of MZmine. You can probably solve it by googling a bit, e.g. https://stackoverflow.com/questions/2044672/ioexception-too-many-open-files

**Comment by metabolon1** [comment]
This is an issue with open file limit. You can check your limits as follows:
```
ulimit -Hn   # hard limit on number of open files
ulimit -Sn    # soft limit on number of open files
```

The hard limit can only be changed by someone with root access, but the soft limit can be increased up to the hard limit by any user. Note that this only works for a given session; once the shell is closed, the soft limit reverts back to the default. For example, to increase the soft limit to 262144 open files :

```
ulimit -n 262144
```
If one wants to permanently change these limits, they must do so by adding additional lines to the limits.conf file

```
vi /etc/security/limits.conf
```

Details can be found here:
https://www.tecmint.com/increase-set-open-file-limits-in-linux/
http://www.lagmonster.org/docs/vi.html
