### ISSUE TITLE
SIRIUS search in MZmine not working on Windows

### ISSUE THREAD

**Issue by romchal** [mzmine/mzmine2#526]
[15:50:36|INFO|WorkerThread]: Starting processing of task Processing element [C6H14N4O2]+ by FingerIdWebMethod
[15:50:36|INFO|WorkerThread]: Starting processing of task Processing element [C4H12N7O]+ by FingerIdWebMethod
[15:50:36|SEVERE|WorkerThread]: Unhandled exception java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod while processing task Processing element [C6H14N4O2]+ by FingerIdWebMethod(java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod@net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141))
[15:50:36|INFO|WorkerThread]: Starting processing of task Processing element [C8H16NO3]+ by FingerIdWebMethod
java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod
        at net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[15:50:36|SEVERE|WorkerThread]: Unhandled exception java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod while processing task Processing element [C4H12N7O]+ by FingerIdWebMethod(java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod@net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141))
[15:50:36|SEVERE|WorkerThread]: Unhandled exception java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod while processing task Processing element [C8H16NO3]+ by FingerIdWebMethod(java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod@net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141))
java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod
        at net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
java.lang.NoClassDefFoundError: Could not initialize class io.github.msdk.id.sirius.FingerIdWebMethod
        at net.sf.mzmine.modules.peaklistmethods.identification.sirius.FingerIdWebMethodTask.run(FingerIdWebMethodTask.java:141)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)

**Comment by tomas-pluskal** [comment]
Should be fixed in MZmine version 2.41.2.
