### ISSUE TITLE
Neutral loss filtering error

### ISSUE THREAD

**Issue by bjonnh** [mzmine/mzmine2#556]
### Setup

I am reporting a problem with MZmine 2 version 2.38.
My operating system is a Linux 64.

Below I pasted the exact output of the following commands:
```
java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+4)
OpenJDK 64-Bit Server VM (build 11.0.3+4, mixed mode)
```

### Expected behavior

When doing a filtering of a peak-list, I would like to be able to search for a specific neutral loss by value OR  molecular formula. 

### Actual behavior

First, it is not possible to put either value or the molecule, the window asks for both (but the help says that if a molecule is set, then value is not taken into account).

Adding a formula and a mass, it then crash:

16:34:32|FINEST|MainMenu]: Starting module Neutral loss filter with parameters Peak lists: 215_MSMS_1-35_01_3004.mzXML filtered chromatogramsADAP deconvoluted deisotoped, m/z tolerance: 0.01 m/z or 5.0 ppm, Check RT: true, Retention time tolerance: 0.1 min, Minimum height: 100.0, Neutral loss (m/z): 16.02, Molecule: NH2, Name suffix: auto
[16:34:32|FINEST|TaskQueue]: Adding task "Got paramenters..." to the task controller queue
[16:34:32|INFO|WorkerThread]: Starting processing of task Got paramenters...
[16:34:32|SEVERE|WorkerThread]: Unhandled exception java.lang.NullPointerException while processing task Got paramenters...(java.lang.NullPointerException@net.sf.mzmine.modules.peaklistmethods.filtering.neutralloss.NeutralLossFilterTask.setUpDiff(NeutralLossFilterTask.java:292))
java.lang.NullPointerException
	at net.sf.mzmine.modules.peaklistmethods.filtering.neutralloss.NeutralLossFilterTask.setUpDiff(NeutralLossFilterTask.java:292)
	at net.sf.mzmine.modules.peaklistmethods.filtering.neutralloss.NeutralLossFilterTask.run(NeutralLossFilterTask.java:116)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)

### Steps to reproduce the problem

Create a peaklist.
Go to filtering, Neutral loss filter. enter parameters :
m/z tolerance: 0.01 m/z or 5.0 ppm, Check RT: true, Retention time tolerance: 0.1 min, Minimum height: 100.0, Neutral loss (m/z): 16.02, Molecule: NH2, Name suffix: auto

**Comment by tomas-pluskal** [comment]
Hi, thanks for the report!

@SteffenHeu @robinschmid Could you please take a look at this?

**Comment by robinschmid** [comment]
Thanks for reporting. 
It is a weird behaviour of the CDK. It generates a formula composed of isotopes without an exact mass.

I am going to push a fix.

**Comment by robinschmid** [comment]
I have a small fix for this issue (see PR #557 )

However, I have encountered another problem. The filter seems to combine random rows. The retention time tolerance is not taken into account and the ppm distance is at random numbers as high as 8000.

@SteffenHeu can you take a look at this?

**Comment by robinschmid** [comment]
Thanks steffen, you've fixed it.
Maybe we could come up with a new naming convention to allow sorting and easy spotting of pairs?

This is the comment that is added so far. 
![image](https://user-images.githubusercontent.com/10366914/55476756-b5739c00-5617-11e9-994c-81f97a78b6ef.png)

Maybe we could change it to
ParentID=2014; ChildID=1764 (NH2; 0.0 ppm) PARENT
ParentID=2014; ChildID=1764 (NH2; 0.0 ppm) CHILD
