### ISSUE TITLE
ADAPChromatogramBuilderTask fails

### ISSUE THREAD

**Issue by glerny** [mzmine/mzmine2#570]
### Setup

I am reporting a problem with MZmine 2 version 2.39 and before 

My operating system is  64-bit.

Below I pasted the exact output of the following commands:
```
java -version

[12:14:18|INFO|ADAPChromatogramBuilderTask]: Started chromatogram builder on a-SampleA_1
[12:14:19|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalStateException: Incorrect range [NaN, NaN] for m/z NaN while processing task Detecting chromatograms in a-SampleA_1(java.lang.IllegalStateException: Incorrect range [NaN, NaN] for m/z NaN@net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChromatogramBuilderTask.run(ADAPChromatogramBuilderTask.java:332))
java.lang.IllegalStateException: Incorrect range [NaN, NaN] for m/z NaN
        at net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChromatogramBuilderTask.run(ADAPChromatogramBuilderTask.java:332)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)

``

**Comment by robinschmid** [comment]
Hey

please give us all the parameter values that you have entered for mass detection and the ADAP chromatogram builder.

It seems like your input for m/z tolerance is wrong. NaN means "not a number".

Cheers
Robin

**Comment by glerny** [comment]
Hi Robin,

You can find the print screen of the conditions attached. I believe it is more a problem with the mzML files (converted from TIF to mzML with MSConvert) before or after the MassDetection step (exact mass with a threshold at 1,000) as the same parameters work with other files. I assume the NaN values result from one of those two steps and this case is not taken into account by the ADAP algorithms.  I just test it using a threshold at 10,000 for the MassDetection (exact mass with a threshold at 10,000) and in this case, the ADAP algorithms work, so I definitely believe that during the centroidisation some errors occur that generate NaN values that bugged the ADAP algorithms (the chromatogram builder work through).  If you want to test the mzML files are here:  https://drive.google.com/drive/folders/1dP_fcDE1U7bDrVrMVajUc1NkRz7SVDjr?usp=sharing


![ADAP](https://user-images.githubusercontent.com/11735178/57076025-743ade80-6ce0-11e9-9516-8f638e179b19.jpg)

Best

Guillaume

**Comment by tomas-pluskal** [comment]
@asmirn1 Alex, could you please take a look at this?

**Comment by tomas-pluskal** [comment]
@asmirn1 I could reproduce this error with the downloaded file ```20170326-960MIX_SampleA_1.mzML``` and the following steps:

<img width="790" alt="Screen Shot 2019-05-02 at 14 30 48" src="https://user-images.githubusercontent.com/1796692/57097935-f1695200-6ce6-11e9-956f-23b963ff9b02.png">

<img width="802" alt="Screen Shot 2019-05-02 at 14 31 00" src="https://user-images.githubusercontent.com/1796692/57097946-f4644280-6ce6-11e9-92a9-459d78f38f9e.png">

<img width="640" alt="Screen Shot 2019-05-02 at 14 30 03" src="https://user-images.githubusercontent.com/1796692/57097955-f6c69c80-6ce6-11e9-9855-d33ec39db962.png">

**Comment by asmirn1** [comment]
Yes. I'll download the files and check the algorithm.

**Comment by asmirn1** [comment]
I've made a pull request with a bugfix.
