### ISSUE TITLE
Running MZmine on linux cluster

### ISSUE THREAD

**Issue by adelabriere** [mzmine/mzmine2#574]
### Setup

I have a problem running multiples instances of MZmine on a linux cluster using LSF. I m doing that to test multiples parameters sets at the same times, I m generating all the required xml files programmatically before that.

I used the exact same setup succesfully on small mzML to test (10 MB) and now I m trying to run the script on 100MB mzML files.

If I don't specifiy an HEAP_SIZE on these new files in the start script, MZmine sems to run but greatly exceed the memory threshold allocated for each core and is therefore killed.

If I modify the HEAP_SIZE MZmine visibly try to run in graphical mode given these X11 errors and fail.

**Running the the same MZmine version with any of the XML files directly on the head of the cluster works !**

Any help or insights would be appreciated

Installed versions :
java  1.8.91
MZmine 2.39

Here is the error message :

> [9:10:32|INFO|MZmineCore]: Starting MZmine 2.39
> [9:10:32|FINE|TmpFileCleanup]: Checking for old temporary files...
> [9:10:32|FINE|MZmineCore]: Loading core classes..
> [9:10:32|FINE|MZmineCore]: Initializing core classes..
> ...All the modules Loading
> [9:10:33|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.tools.isotopepatternpreview.IsotopePatternPreviewModule
> [9:10:33|FINE|MZmineCore]: Initializing GUI
> [9:10:33|SEVERE|MZmineCore]: Could not initialize GUI(java.lang.reflect.InvocationTargetException@java.awt.EventQueue.invokeAndWait(EventQueue.java:1321))
> java.lang.reflect.InvocationTargetException
> 	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
> 	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
> 	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
> 	at net.sf.mzmine.main.MZmineCore.main(MZmineCore.java:170)
> Caused by: java.awt.HeadlessException: 
> No X11 DISPLAY variable was set, but this program performed an operation which requires it.
> 	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
> 	at java.awt.Window.<init>(Window.java:536)
> 	at java.awt.Frame.<init>(Frame.java:420)
> 	at java.awt.Frame.<init>(Frame.java:385)
> 	at javax.swing.JFrame.<init>(JFrame.java:189)
> 	at net.sf.mzmine.desktop.impl.MainWindow.<init>(MainWindow.java:64)
> 	at net.sf.mzmine.main.MZmineCore$1.run(MZmineCore.java:148)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=1
> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by adelabriere** [comment]
I m closing the issue as this behavior was coming from a mistake on my side.
