### ISSUE TITLE
Concurrent modification of identities

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine2#606]
Hey all,

I got a concurrent modification exception (only once) during MS/MS spectral matching. The exception points to SimplePeakListRow.addPeakIdentity. Maybe this method should be changed to (instead of having the whole method beeing synchronized):

```
public void addPeakIdentity(PeakIdentity identity, boolean preferred) {

    // Verify if exists already an identity with the same name
    synchronized (identities) {
      for (PeakIdentity testId : identities) {
        if (testId.getName().equals(identity.getName())) {
          return;
        }
      }

      identities.add(identity);
      if ((preferredIdentity == null) || (preferred)) {
        setPreferredPeakIdentity(identity);
      }
    }
  }
```

What do you think?
I actually thought Vectors are thread safe.

``` java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
	at java.util.Vector$Itr.next(Vector.java:1137)
	at net.sf.mzmine.datamodel.impl.SimplePeakListRow.addPeakIdentity(SimplePeakListRow.java:238)
	at net.sf.mzmine.modules.peaklistmethods.identification.spectraldbsearch.sort.SortSpectralDBIdentitiesTask.sortIdentities(SortSpectralDBIdentitiesTask.java:150)
	at net.sf.mzmine.modules.peaklistmethods.identification.spectraldbsearch.sort.SortSpectralDBIdentitiesTask.sortIdentities(SortSpectralDBIdentitiesTask.java:114)
	at net.sf.mzmine.modules.peaklistmethods.identification.spectraldbsearch.PeakListSpectralMatchTask.run(PeakListSpectralMatchTask.java:188)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)```

**Comment by tomas-pluskal** [comment]
Hi @robinschmid 
Vectors are synchronized, but concurrent modification can still happen when one thread is iterating over the vector and another thread modifies it during the iteration. In other words, synchronized doesn't mean the whole iteration block is synchronized.

I think your proposed solution actually doesn't change much, because the addPeakIdentity() and removePeakIdentity() methods are already synchronized, so only a single thread can access the Vector at one time in these methods. I think the problem probably lies in the fact that the setPreferredPeakIdentity() method is not synchronized, but it also modifies (in some cases) the Vector. I will make it synchronized and let me know if you notice this problem again.

**Comment by robinschmid** [comment]
this should be fixed - I had no issues anymore
