### ISSUE TITLE
Error in importing Raw data

### ISSUE THREAD

**Issue by srezaei268** [mzmine/mzmine2#623]
MZmine 2.40.1
Java 8 update 211
Windows 10, 64bit.
![1](https://user-images.githubusercontent.com/52181352/60058575-7dc43f80-96ae-11e9-85d0-84f93406d857.jpg)
![2](https://user-images.githubusercontent.com/52181352/60058579-8157c680-96ae-11e9-9d05-1b918b26c234.jpg)

I can not import my raw data files to MZmine. This error (800736b1.(Native File Read Task.java:198)) appears each time. I'll appreciate your help.

**Comment by robinschmid** [comment]
Hey,

it is always good if you copy and paste the exception stack trace from the console. Are you trying to import thermo raw data?
Can you import the data with one of the previous versions?

Cheers
Robin

**Comment by srezaei268** [comment]
This is the exception stack trace from the console when I want to import raw data from my laptop:

----------
[8:23:42|FINEST|net.sf.mzmine.desktop.impl.MainMenu]: Setting parameters for module Raw data import
[8:23:46|FINEST|net.sf.mzmine.desktop.impl.MainMenu]: Starting module Raw data import with parameters Raw data file names: [C:\Users\Pars\Desktop\LCMS data\cntflower1.raw]
[8:23:46|FINEST|net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule]: File C:\Users\Pars\Desktop\LCMS data\cntflower1.raw type detected as THERMO_RAW
[8:23:46|FINEST|net.sf.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Opening file C:\Users\Pars\Desktop\LCMS data\cntflower1.raw" to the task controller queue
[8:23:46|INFO|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Opening file C:\Users\Pars\Desktop\LCMS data\cntflower1.raw
[8:23:46|INFO|net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask]: Opening file C:\Users\Pars\Desktop\LCMS data\cntflower1.raw
java.io.IOException: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 800736b1.
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.readRAWDump(NativeFileReadTask.java:198)
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.run(NativeFileReadTask.java:133)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[8:23:47|SEVERE|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Error of task Opening file C:\Users\Pars\Desktop\LCMS data\cntflower1.raw: java.io.IOException: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class (NativeFileReadTask.java:198)SID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 800736b1.

----------

I've tried all the previous version but each time I receive the same error. This error just appear in my laptop no matter which version I am using. I can import raw data from my desk computer. This is stack trace from the console of my desk computer:

-----------
[8:34:57|FINEST|net.sf.mzmine.util.InetUtils]: Retrieved 7 characters from http:
//mzmine.github.io/version.txt
[8:35:10|FINEST|net.sf.mzmine.desktop.impl.MainMenu]: Setting parameters for mod
ule Raw data import
[8:35:17|FINEST|net.sf.mzmine.desktop.impl.MainMenu]: Starting module Raw data i
mport with parameters Raw data file names: [C:\Users\srezaeicher\Desktop\LCMS da
ta\cntflower1.raw]
[8:35:17|FINEST|net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImport
Module]: File C:\Users\srezaeicher\Desktop\LCMS data\cntflower1.raw type detecte
d as THERMO_RAW
[8:35:17|FINEST|net.sf.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Opening
file C:\Users\srezaeicher\Desktop\LCMS data\cntflower1.raw" to the task controll
er queue
[8:35:17|INFO|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Starting processing
of task Opening file C:\Users\srezaeicher\Desktop\LCMS data\cntflower1.raw
[8:35:17|INFO|net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.Nat
iveFileReadTask]: Opening file C:\Users\srezaeicher\Desktop\LCMS data\cntflower1
.raw
[8:35:23|FINEST|net.sf.mzmine.project.impl.RawDataFileImpl]: Writing of scans to
 file C:\Users\SREZAE~1\AppData\Local\Temp\mzmine155754367225091601.scans finish
ed
[8:35:23|INFO|net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.Nat
iveFileReadTask]: Finished parsing C:\Users\srezaeicher\Desktop\LCMS data\cntflo
wer1.raw, parsed 14831 scans
[8:35:23|INFO|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Processing of task O
pening file C:\Users\srezaeicher\Desktop\LCMS data\cntflower1.raw done, status F
INISHED

---------

Thank you very much.

**Comment by tomas-pluskal** [comment]
Try installing ProteoWizard (http://proteowizard.sourceforge.net/download.html) and after that, try the import in MZmine again. It's possible that it's missing some libraries and installing ProteWizard will fix the issue.

**Comment by srezaei268** [comment]
Hi,
I have installed ProteoWizard and imported data in MZmine again but the same error appears.

**Comment by tomas-pluskal** [comment]
Have you restarted Windows after the installation?

**Comment by srezaei268** [comment]
Yes. I even tried importing data in other version of MZmine but same error pops up.

-------
[15:26:39|FINEST|InetUtils]: Retrieving data from URL http://mzmine.github.io/version.txt
[15:26:39|FINEST|InetUtils]: Retrieved 7 characters from http://mzmine.github.io/version.txt
[15:26:39|INFO|NewVersionCheck]: An updated version is available: MZmine 2.40.1
[15:26:42|FINEST|MainMenu]: Setting parameters for module Raw data import
[15:26:48|FINEST|MainMenu]: Starting module Raw data import with parameters Raw data file names: [E:\LCMS data\cntleaf2.raw]
[15:26:48|FINEST|RawDataImportModule]: File E:\LCMS data\cntleaf2.raw type detected as THERMO_RAW
[15:26:48|FINEST|TaskQueue]: Adding task "Opening file E:\LCMS data\cntleaf2.raw" to the task controller queue
[15:26:48|INFO|WorkerThread]: Starting processing of task Opening file E:\LCMS data\cntleaf2.raw
[15:26:48|INFO|NativeFileReadTask]: Opening file E:\LCMS data\cntleaf2.raw
java.io.IOException: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 800736b1.
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.readRAWDump(NativeFileReadTask.java:198)
        at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.run(NativeFileReadTask.java:133)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[15:26:49|SEVERE|WorkerThread]: Error of task Opening file E:\LCMS data\cntleaf2.raw: java.io.IOException: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C (NativeFileReadTask.java:198)ue to the following error: 800736b1.

**Comment by tomas-pluskal** [comment]
How about if you use MSConvert from ProteoWizard to convert your .raw file into .mzML format, does that work?

**Comment by srezaei268** [comment]
Thank you very much Tomas. That worked.
![3](https://user-images.githubusercontent.com/52181352/60131599-5a0d0200-975f-11e9-8f17-32bd5fc7099e.jpg)

**Comment by tomas-pluskal** [comment]
Okay. I don't know why the import in MZmine is not working, but it seems like something specific to your laptop so it's going to be hard to reproduce and debug.

**Comment by srezaei268** [comment]
Actually I am a new learner and user of MZmine and I am using it for my metabolomics project.
So in case of using .mzML format instead of .raw format, would it be problem in further processing and analyzing?

**Comment by tomas-pluskal** [comment]
No problem, mzML is an open, well supported data format.

**Comment by srezaei268** [comment]
Great.
Thank you very much for your help.
