### ISSUE TITLE
Can't connect to X11 window server using 'localhost:12.0' as the value of the DISPLAY variable.@sun.awt

### ISSUE THREAD

**Issue by xiaodfeng** [mzmine/mzmine2#636]
### Setup

I am reporting a problem with MZmine 2 version (*2.40.1*). 
My operating system is (*Linux server*).

Below I pasted the exact output of the following commands:
```
java -version 1.8.0_212
R --version 3.5.0
(*openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

[9:37:19|INFO|net.sf.mzmine.main.MZmineCore]: Starting MZmine 2.40.1
[9:37:19|FINE|net.sf.mzmine.main.TmpFileCleanup]: Checking for old temporary files...
[9:37:19|FINE|net.sf.mzmine.main.MZmineCore]: Loading core classes..
[9:37:19|FINE|net.sf.mzmine.main.MZmineCore]: Initializing core classes..
[9:37:19|FINE|net.sf.mzmine.main.MZmineCore]: Loading modules
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectload.ProjectLoadModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveAsModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectclose.ProjectCloseModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.batchmode.BatchModeModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.rawdataexport.RawDataExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.merge.RawFileMergeModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.exportscans.ExtractScansModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.shoulderpeaksfilter.ShoulderPeaksFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.ChromatogramBuilderModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChromatogramBuilderModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.gridmass.GridMassModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.manual.ManualPeakPickerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.msms.MsMsPeakPickerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scanfilters.ScanFiltersModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.cropper.CropFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.baselinecorrection.BaselineCorrectionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.alignscans.AlignScansModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scansmoothing.ScanSmoothingModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.orderdatafiles.OrderDataFilesModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.orderpeaklists.OrderPeakListsModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.join.JoinAlignerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.hierarchical.HierarAlignerGcModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.ransac.RansacAlignerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.adap3.ADAP3AlignerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.csvexport.CSVExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.metaboanalystexport.MetaboAnalystExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabexport.MzTabExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.sqlexport.SQLExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlexport.XMLExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.casmiimport.CasmiImportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabimport.MzTabImportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlimport.XMLImportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mspexport.MSPExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mgfexport.MGFExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.gnpsexport.GNPSExportAndSubmitModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.siriusexport.SiriusExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.multithreaded.MultiThreadPeakFinderModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.samerange.SameRangeGapFillerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.deisotoper.IsotopeGrouperModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.isotopeprediction.IsotopePatternCalculator
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.isotopepeakscanner.IsotopePeakScannerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.smoothing.SmoothingModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.shapemodeler.ShapeModelerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.peakextender.PeakExtenderModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.adap3decompositionV1_5.ADAP3DecompositionV1_5Module
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.adap3decompositionV2.ADAP3DecompositionV2Module
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.groupms2.GroupMS2Module
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.duplicatefilter.DuplicateFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.rowsfilter.RowsFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.peakcomparisonrowfilter.PeakComparisonRowFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.peakfilter.PeakFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.clearannotations.PeaklistClearAnnotationsModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.neutralloss.NeutralLossFilterModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.rtnormalizer.RTNormalizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.linear.LinearNormalizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.standardcompound.StandardCompoundNormalizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.cvplot.CVPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.logratioplot.LogratioPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.PCAPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.CDAPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.SammonsPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.clustering.ClusteringModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.heatmaps.HeatMapModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.significance.SignificanceModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.spectraldbsearch.LocalSpectralDBSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.spectraldbsearch.sort.SortSpectralDBIdentitiesModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.customdbsearch.CustomDBSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulaprediction.FormulaPredictionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.fragmentsearch.FragmentSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.adductsearch.AdductSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.complexsearch.ComplexSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.OnlineDBSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.lipididentification.LipidSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.camera.CameraSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.nist.NistMsSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulapredictionpeaklist.FormulaPredictionPeakListModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.ms2search.Ms2SearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.sirius.SiriusProcessingModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.gnpsresultsimport.GNPSResultsImportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.tic.TICVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.SpectraVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.twod.TwoDVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.threed.ThreeDVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.msms.MsMsVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.neutralloss.NeutralLossVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.mzhistogram.MZDistributionHistoModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.PeakListTableModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.IsotopePatternExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.MSMSExportModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.scatterplot.ScatterPlotVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.histogram.HistogramVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.infovisualizer.InfoVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.intensityplot.IntensityPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.kendrickmassplot.KendrickMassPlotModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.vankrevelendiagram.VanKrevelenDiagramModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.productionfilter.ProductIonFilterVisualizerModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrangecalculator.MzRangeMassCalculatorModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrangecalculator.MzRangeFormulaCalculatorModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.tools.isotopepatternpreview.IsotopePatternPreviewModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.spectraidentification.spectraldatabase.SpectraIdentificationSpectralDatabaseModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.spectraldbsubmit.LibrarySubmitModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.spectraidentification.customdatabase.CustomDBSpectraSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.spectraidentification.lipidsearch.LipidSpectraSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.spectraidentification.onlinedatabase.OnlineDBSpectraSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.spectraidentification.sumformula.SumFormulaSpectraSearchModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.datapointprocessing.DataPointProcessingManager
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.datapointprocessing.massdetection.DPPMassDetectionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.datapointprocessing.identification.sumformulaprediction.DPPSumFormulaPredictionModule
[9:37:19|FINEST|net.sf.mzmine.main.MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.simplespectra.datapointprocessing.isotopes.deisotoper.DPPIsotopeGrouperModule
[9:37:19|FINEST|net.sf.mzmine.main.impl.MZmineConfigurationImpl]: Loading desktop configuration
[9:37:19|FINEST|net.sf.mzmine.main.impl.MZmineConfigurationImpl]: Loading last projects
[9:37:19|FINEST|net.sf.mzmine.main.impl.MZmineConfigurationImpl]: Loading modules configuration
[9:37:20|INFO|net.sf.mzmine.main.impl.MZmineConfigurationImpl]: Loaded configuration from file conf/config.xml
[9:37:20|INFO|net.sf.mzmine.modules.batchmode.BatchModeModule]: Running batch from file /home/p282719/MZmine-2.40.1/Batch.xml
[9:37:20|INFO|net.sf.mzmine.modules.batchmode.BatchTask]: Starting a batch of 7 steps
[9:37:20|INFO|net.sf.mzmine.modules.batchmode.BatchTask]: Starting step # 1
[9:37:20|FINEST|net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule]: File /data/p282719/20190413_lipidomics_pipeline_comparison/Centroid/IS1-8/PlasmaIS1-8_13.mzML type detected as MZML
[9:37:20|FINEST|net.sf.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Opening file /data/p282719/20190413_lipidomics_pipeline_comparison/Centroid/IS1-8/PlasmaIS1-8_13.mzML" to the task controller queue
[9:37:20|SEVERE|net.sf.mzmine.modules.batchmode.BatchModeModule]: Error while running batch(java.awt.AWTError: Can't connect to X11 window server using 'localhost:12.0' as the value of the DISPLAY variable.@sun.awt.X11GraphicsEnvironment.initDisplay(Native Method))
java.awt.AWTError: Can't connect to X11 window server using 'localhost:12.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1740)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at net.sf.mzmine.taskcontrol.impl.TaskQueue.addWrappedTask(TaskQueue.java:91)
	at net.sf.mzmine.taskcontrol.impl.TaskControllerImpl.addTasks(TaskControllerImpl.java:123)
	at net.sf.mzmine.taskcontrol.impl.TaskControllerImpl.addTasks(TaskControllerImpl.java:104)
	at net.sf.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:184)
	at net.sf.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:90)
	at net.sf.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:91)
	at net.sf.mzmine.main.MZmineCore.main(MZmineCore.java:252)
*)
```

### Expected behavior

(*Run the mzMine on Linux server using batch mode*)

### Actual behavior

(*Obtained an error: Can't connect to X11 window server using 'localhost:12.0' as the value of the DISPLAY variable.@sun.awt*)

### Steps to reproduce the problem
1. The following commands works well on my Linux server:
```
cd /path/to/file/directory/
chmod +x startMZmine_Linux.sh
./startMZmine_Linux.sh /path/to/batch/file/BatchFileName.xml
```

2. However, if I run the following commands:
```
cd /path/to/file/directory/
sbatch startMZmine_Linux.sh  /path/to/batch/file/BatchFileName.xml
```
I will get the error: 

> Can't connect to X11 window server using 'localhost:12.0' as the value of the DISPLAY variable.@sun.awt.

**Comment by asmirn1** [comment]
As I understand, this error indicates that MZmine is trying to run in the GUI mode instead of the batch mode. Maybe the problem is that when you execute 
```
sbatch startMZmine_Linux.sh  /path/to/batch/file/BatchFileName.xml
``` 
the argument `/path/to/batch/file/BatchFileName.xml` is not passed correctly to sbatch/Slurm. I would check the logs for Slurm to see what command is actually executed: 
```
sbatch startMZmine_Linux.sh
``` 
or 
```
sbatch startMZmine_Linux.sh  /path/to/batch/file/BatchFileName.xml
```

**Comment by tomas-pluskal** [comment]
It seems your cluster environment does not have an X server (which is fine), but you have the DISPLAY variable set in your environment, which causes this error. I think if you unset the DISPLAY variable, it should work fine.

**Comment by xiaodfeng** [comment]
@tomas-pluskal @asmirn1 Thank you for the suggestions. Problem sovled!
I run `unset DISPLAY` in command, then run the `sbatch startMZmine_Linux.sh  /path/to/batch/file/BatchFileName.xml` command again. It works now!
