### ISSUE TITLE
Error while running ADAP peakpicking in batch mode on Linux cluster

### ISSUE THREAD

**Issue by adelabriere** [mzmine/mzmine2#705]
* My operating system: Linux centOS 7 on a cluster
* My MZmine version: 2.51 (Bug does not happen with version 2.39 and happens with version 2.41)

I run in parallel multiple peakpicking using ADAP in batch mode on a cluster to process a large number of files. The batch files are generated programmatically. This works with MZmine version 2.39 but not in version 2.51.
The batch step are the following : 

1. RawDataImportModule
2. MassDetectionModule (Centroids)
3. ADAPChromatogramBuilderModule
4. DeconvolutionModule (Wavelets (ADAP))
5. CSVExportModule

Here is the error message that I have on the second step :
```
[14:31:07|INFO|net.sf.mzmine.modules.batchmode.BatchTask]: Starting step # 2
[14:31:07|SEVERE|net.sf.mzmine.modules.batchmode.BatchModeModule]: Error while running batch(java.lang.NullPointerException@net.sf.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:136))
java.lang.NullPointerException
	at net.sf.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:136)
	at net.sf.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:90)
	at net.sf.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:91)
	at net.sf.mzmine.main.MZmineCore.main(MZmineCore.java:243)
```
The batch file is valid, it processes if I run it on my own machine with the same java version on windows 10. The bug only occurs on the cluster with version above 2.39 on the cluster. It also occurs if I don t parallelize anything on the cluster.

Any help would be greatly appreciated !

Alexis

**Comment by tomas-pluskal** [comment]
Please attach the batch file, thanks!

**Comment by adelabriere** [comment]
Here it is :
```
<?xml version="1.0"?>
<batch>
  <batchstep method="net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule">
    <parameter name="Raw data file names">
      <file>/cluster/scratch/dalexis/quick_test/mzML/126_6_21_D_8_3_6_n.mzML</file>
    </parameter>
  </batchstep>
  <batchstep method="net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule">
    <parameter name="BATCH_LAST_FILES"/>
    <parameter name="Scans">
      <ms_level>1</ms_level>
    </parameter>
    <parameter name="Mass detector" selected="Centroid">
      <module name="Centroid">
        <parameter name="Noise level">100</parameter>
      </module>
      <module name="Exact mass">
        <parameter name="Noise level"/>
      </module>
      <module name="Local maxima">
        <parameter name="Noise level"/>
      </module>
      <module name="Recursive threshold">
        <parameter name="Noise level"/>
        <parameter name="Min m/z peak width"/>
        <parameter name="Max m/z peak width"/>
      </module>
      <module name="Wavelet transform">
        <parameter name="Noise level"/>
        <parameter name="Scale level"/>
        <parameter name="Wavelet window size (%)"/>
      </module>
    </parameter>
    <parameter name="Mass list name">masses</parameter>
    <parameter name="false"/>
  </batchstep>
  <batchstep method="net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChromatogramBuilderModule">
    <parameter name="BATCH_LAST_FILES"/>
    <parameter name="Scans">
      <ms_level>1</ms_level>
    </parameter>
    <parameter name="Mass list">masses</parameter>
    <parameter name="Min group size in # of scans">5</parameter>
    <parameter name="Group intensity threshold">20</parameter>
    <parameter name="Min highest intensity">100</parameter>
    <parameter name="m/z tolerance">
      <absolutetolerance>0.005</absolutetolerance>
      <ppmtolerance>20</ppmtolerance>
    </parameter>
    <parameter name="Suffix">chromatograms</parameter>
  </batchstep>
  <batchstep method="net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionModule">
    <parameter name="BATCH_LAST_PEAKLISTS"/>
    <parameter name="Suffix">deconvoluted</parameter>
    <parameter name="Algorithm" selected="Wavelets (ADAP)">
      <module name="Baseline cut-off">
        <parameter name="Min peak height"/>
        <parameter name="Peak duration range (min)">
          <min>0</min>
          <max>10</max>
        </parameter>
        <parameter name="Baseline level"/>
      </module>
      <module name="Noise amplitude">
        <parameter name="Min peak height"/>
        <parameter name="Peak duration range (min)">
          <min>0</min>
          <max>10</max>
        </parameter>
        <parameter name="Amplitude of noise"/>
      </module>
      <module name="Savitzky-Golay">
        <parameter name="Min peak height"/>
        <parameter name="Peak duration range (min)">
          <min>0</min>
          <max>10</max>
        </parameter>
        <parameter name="Derivative threshold level"/>
      </module>
      <module name="Local minimum search">
        <parameter name="Chromatographic threshold"/>
        <parameter name="Search minimum in RT range (min)"/>
        <parameter name="Minimum relative height"/>
        <parameter name="Minimum absolute height"/>
        <parameter name="Min ratio of peak top/edge"/>
        <parameter name="Peak duration range (min)">
          <min>0</min>
          <max>10</max>
        </parameter>
      </module>
      <module name="Wavelets (XCMS)">
        <parameter name="S/N threshold">10</parameter>
        <parameter name="Wavelet scales">
          <min>0.25</min>
          <max>5</max>
        </parameter>
        <parameter name="Peak duration range">
          <min>0</min>
          <max>10</max>
        </parameter>
        <parameter name="Peak integration method">Use smoothed data</parameter>
        <parameter name="R engine">RCaller</parameter>
      </module>
      <module name="Wavelets (ADAP)">
        <parameter name="S/N threshold">3</parameter>
        <parameter name="S/N estimator" selected="Intensity window SN">
          <module name="Intensity window SN"/>
          <module name="Wavelet Coeff. SN">
            <parameter name="Peak width mult.">3</parameter>
            <parameter name="abs(wavelet coeffs.)">true</parameter>
          </module>
        </parameter>
        <parameter name="min feature height">1000</parameter>
        <parameter name="coefficient/area threshold">110</parameter>
        <parameter name="Peak duration range">
          <min>0.01</min>
          <max>0.1</max>
        </parameter>
        <parameter name="RT wavelet range">
          <min>0.001</min>
          <max>0.05</max>
        </parameter>
      </module>
    </parameter>
    <parameter name="m/z center calculation">CenterFunction</parameter>
    <parameter name="false"/>
    <parameter name="false"/>
    <parameter name="Remove original peak list">false</parameter>
  </batchstep>
  <batchstep method="net.sf.mzmine.modules.peaklistmethods.io.csvexport.CSVExportModule">
    <parameter name="BATCH_LAST_PEAKLISTS"/>
    <parameter name="Filename">/cluster/scratch/dalexis/quick_test/results/ADAP/peaktables/peaktable_1_471253988657d543db968c1124297cec.csv</parameter>
    <parameter name="Field separator">,</parameter>
    <parameter name="Export common elements">
      <item>Export row ID</item>
      <item>Export row m/z</item>
      <item>Export row retention time</item>
    </parameter>
    <parameter name="Export data file elements">
      <item>Peak m/z</item>
      <item>Peak RT</item>
      <item>Peak RT start</item>
      <item>Peak RT end</item>
      <item>Peak height</item>
      <item>Peak area</item>
      <item>Peak charge</item>
      <item>Peak FWHM</item>
      <item>Peak m/z min</item>
      <item>Peak m/z max</item>
    </parameter>
    <parameter name="Export quantitation results and other information">true</parameter>
    <parameter name="Identification separator">,</parameter>
    <parameter name="Filter rows">ALL</parameter>
  </batchstep>
</batch>
```

**Comment by tomas-pluskal** [comment]
I don't think this batch file is valid for recent versions of MZmine. You should try to load this batch into the latest MZmine version, double-check all parameter values (especially the "Raw data files" parameter of all steps), and then save it as a new batch file. I bet it will work afterwards.

The main issue is that your batch file contains this:
```
<parameter name="BATCH_LAST_PEAKLISTS"/>
```
while it should actually be this:
```
<parameter name="Raw data files" type="BATCH_LAST_FILES"/>
```

I will try to add more checks and error messages to the process.

**Comment by adelabriere** [comment]
Thanks for pointing that out,
 
I ll correct this and test it today.

**Comment by adelabriere** [comment]
It is working perfectly fine and faster than before,

Thanks a lot !
