### ISSUE TITLE
MZmine batch mode for MS-MS extraction crash when there is no MS-MS

### ISSUE THREAD

**Issue by adelabriere** [mzmine/mzmine2#720]
Dear MZmine team,

I'm trying to extract MS-MS automatically from a large number of MS-MS runs. This number if too large to us MZmine for the alignement step in so I have an external way to do it, therefore I just do the peak picking and export hte peaktable.

I also want to extract the MS-MS spectra **if they exist** to do so I use the following batch steps :

1. Raw data import
2. Mass detection (MS1)
3. Mass detection (MS2)
4. ADAP chronmatogram builder
5. Deconvolution module (ADAP)
6. CSV export for the peaklist (I need mzmin, mzmax, rtmin, rtmax)
7. Join Aligner
8. Sort Features
9. Export GNPS

However if there is no MS-MS spectra in .mzML file, the processing never finish and the message is the following : 
```
[12:34:41|SEVERE|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Unhandled exception io.github.msdk.MSDKRuntimeException: No MS/MS scans exported. while processing task Exporting GNPS of feature list(s) [Aligned feature list] to MGF file(s)(io.github.msdk.MSDKRuntimeException: No MS/MS scans exported.@net.sf.mzmine.modules.peaklistmethods.io.gnpsexport.GNPSmgfExportTask.export(GNPSmgfExportTask.java:282))
io.github.msdk.MSDKRuntimeException: No MS/MS scans exported.
        at net.sf.mzmine.modules.peaklistmethods.io.gnpsexport.GNPSmgfExportTask.export(GNPSmgfExportTask.java:282)
        at net.sf.mzmine.modules.peaklistmethods.io.gnpsexport.GNPSmgfExportTask.run(GNPSmgfExportTask.java:146)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)
[12:34:42|SEVERE|net.sf.mzmine.desktop.impl.HeadLessDesktop]: Unhandled exception in task Exporting GNPS of feature list(s) [Aligned feature list] to MGF file(s): io.github.msdk.MSDKRuntimeException: No MS/MS scans exported. (GNPSmgfExportTask.java:282)
[12:34:42|INFO|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Processing of task Exporting feature list(s) [Aligned feature list] to CSV file(s) done, status FINISHED
```
The program never finish, it is just stuck there, which prevent me form processing the file further. 

Is there any solution to this problem ? I think that the fact that no MS-MS spectra in exported could be warning over a severe issue.

My OS is windows 10, and I plan to run this peakpicking in a linux docker. I use MZmine version 2.51

Thanks,
Alexis

**Comment by robinschmid** [comment]
Hey Alexis,

how many (LC-MS) runs are too many? 
Do you use data-dependent acquisition?
Every run should have MS/MS runs?

What are your GNPS export settings? (Do you run your data through GNPS afterwards?)


Yes this should definitely not be a severe issue.

Cheers
Robin

**Comment by lfnothias** [comment]
Hi
If I understand correctly, @adelabriere you don't want to aligned your peaklists.
Therefor the Join Aligner step is not needed. Also, I am not sure if the GNPSExport is capable of exporting results for a (non aligned) peaklist ? @robinschmid ?

**Comment by adelabriere** [comment]
I can align a single file actually without that the export don t work and it has no computational cost. So I do it. Thanks for the quick fix!

**Comment by lfnothias** [comment]
Nice. Good to know ^^

**Comment by robinschmid** [comment]
Have you tried to centroid (and maybe to threshold) your data during conversion? msconvert uses vendor algorithms. This reduces the file size drastically and might push the limits further. 

Would be interesting to know. Moreover, speed of gap-filling was increased drastically by multi-threading a year ago. 

I cannot reproduce your problems. 
1. Mass detection
2. ADAP Chromatogram building
3. Deconvolution (local min search / ADAP Wavelets) (with MS2 scan pairing)
4. GNPS export 

...worked for me.

**Comment by adelabriere** [comment]
Thanks robin for the test it works for me too,

Actually it is my mistake the spectra are not exported using the MGF export function for a single file, but they are using the GNPS export function.

Thanks for the fix,

Alexis
