### ISSUE TITLE
Batch stops at prompt ;)

### ISSUE THREAD

**Issue by minzaroma** [mzmine/mzmine2#763]
### Basic information

* My operating system: Windows 2012 Server R2 Standard
* My MZmine version: 2.42 and 2.52

### What happened

I somehow can't figure out how to properly run a batch mode for several individual projects. I was running a batch on different files like this:

- raw files import (10-20 files)
- (different operations)
- save project as: ...
- close project
- raw files import (next 10-20 ...)
... etc.

Unfortunately, the batch stops by prompting if I really want to close the project. Not adding "close project" will add the next raw files into the same project, producing an exorbitantly large file that can fail to reopen on my system. Maybe the prompt could just be overridden in batch mode, or is there any workaround?

Cheers, Caro

![grafik](https://user-images.githubusercontent.com/52671757/69481877-8368b180-0e15-11ea-9671-ac951dbd67da.png)

**Comment by tomas-pluskal** [comment]
Thanks for the report, I guess we haven't really thought about such use case where someone wants to run a batch over multiple projects. We'll look into this.

**Comment by minzaroma** [comment]
Ok, very cool! If you're at it, maybe also have a look at "open project", which produces a similar prompt. ;)

**Comment by robinschmid** [comment]
You could try to use the headless mode and start multiple runtimes.

**Comment by romchal** [comment]
On windows I suggest to run from command line using .bat file containing:
call mzmine_location project1_batch_script.xml
call mzmine_location project2_batch_script.xml
...

**Comment by minzaroma** [comment]
Thanks, I'll try that!

**Comment by hhabra** [comment]
I realize it's been over a year since this discussion, but I thought I'd add that when trying to invoke "Close Project" on a batch mode file run from the command line (e.g. startMZmine-Windows.bat   multiple_experiment_run.xml), there is an error invoked which I'll print below. As mentioned, individual Batch files for each experiment is a suitable workaround, though it would be easier to have it all run in one go. 

**SEVERE|io.github.mzmine.modules.batchmode.BatchModeModule]: Error while running batch(java.lang.NullPointerException@io.github.mzmine.modules.io.projectclose.ProjectCloseModule.runModule(ProjectCloseModule.java:66))
java.lang.NullPointerException
        at io.github.mzmine.modules.io.projectclose.ProjectCloseModule.runModule(ProjectCloseModule.java:66)
        at io.github.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:194)
        at io.github.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:94)
        at io.github.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:98)
        at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:259)**
