### ISSUE TITLE
Merge MS/MS for GNPS-FBMN export

### ISSUE THREAD

**Issue by whank** [mzmine/mzmine2#796]
### Basic information

* My operating system: Windows
* My MZmine version: 2.53

### What happened:
When using the export/import->export/submit to GNPS-FBMN I chose/entered the following parameters:
- my feature list
- the file name
- the mass list
- Merge MS/MS (experimental): yes -> Setup: -select spectra to merge: across samples -M/z merge mode: weighted average (remove outliners) -Intensity merge mode: Sum intensities -Expected mass deviation: 0.01 m/z or 20.0 ppm -cosine threshold (%): 70 -peak count threshold (%): 20 -isolation window offset (m/z): 0.0000 -isolation window width (m/z): 3.000
-Filter Rows: Only with MS2
Submit to GNPS: no
Open folder: no

This led, when pressing "OK" to the following error:
Unhandled exception java.lang.RuntimeException: Scan modified_CvIII_WH_Sa1_GC1_01_25324.mzXML#867 does not have a mass list masses while processing task Exporting GNPS of feature list(s) [Aligned feature list filtered without] to MGF file(s)(java.lang.RuntimeException: Scan modified_CvIII_WH_Sa1_GC1_01_25324.mzXML#867 does not have a mass list masses@io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeConsecutiveScans(MsMsSpectraMergeModule.java:411))

When I exported without merging Ms/Ms everything was fine. 
I checked the data mentioned in the error message, but there are masses, Ms1 as well as Ms2.

The whole process: 
[14:26:54|FINEST|io.github.mzmine.gui.impl.MainMenu]: Setting parameters for module Export/Submit to GNPS-FBMN
[14:27:18|FINEST|io.github.mzmine.gui.impl.MainMenu]: Starting module Export/Submit to GNPS-FBMN with parameters Feature lists: Aligned feature list filtered without, Filename: C:\Users\wiebk\Documents\Wichtig\Promotion\Laborkram\mzmine\neueparasmoothalles.mgf, Mass list: masses, Merge MS/MS (experimental): true, Filter rows: ONLY WITH MS2, Submit to GNPS: false, Open folder: false
[14:27:18|FINEST|io.github.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Exporting files GNPS feature based molecular networking job" to the task controller queue
[14:27:18|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Exporting files GNPS feature based molecular networking job
[14:27:18|FINEST|io.github.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Exporting GNPS of feature list(s) [Aligned feature list filtered without] to MGF file(s)" to the task controller queue
[14:27:18|FINEST|io.github.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Exporting feature list(s) [Aligned feature list filtered without] to CSV file(s)" to the task controller queue
[14:27:18|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Exporting GNPS of feature list(s) [Aligned feature list filtered without] to MGF file(s)
[14:27:18|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Exporting feature list(s) [Aligned feature list filtered without] to CSV file(s)
[14:27:18|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Processing of task Exporting feature list(s) [Aligned feature list filtered without] to CSV file(s) done, status FINISHED
[14:27:20|SEVERE|io.github.mzmine.taskcontrol.impl.WorkerThread]: Unhandled exception java.lang.RuntimeException: Scan modified_CvIII_WH_Sa1_GC1_01_25324.mzXML#867 does not have a mass list masses while processing task Exporting GNPS of feature list(s) [Aligned feature list filtered without] to MGF file(s)(java.lang.RuntimeException: Scan modified_CvIII_WH_Sa1_GC1_01_25324.mzXML#867 does not have a mass list masses@io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeConsecutiveScans(MsMsSpectraMergeModule.java:411))
java.lang.RuntimeException: Scan modified_CvIII_WH_Sa1_GC1_01_25324.mzXML#867 does not have a mass list masses
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeConsecutiveScans(MsMsSpectraMergeModule.java:411)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeConsecutiveScans(MsMsSpectraMergeModule.java:240)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeFromSameSample(MsMsSpectraMergeModule.java:200)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.lambda$mergeAcrossSamples$6(MsMsSpectraMergeModule.java:182)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.mergeAcrossSamples(MsMsSpectraMergeModule.java:184)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.getMergedSpectra(MsMsSpectraMergeModule.java:136)
        at io.github.mzmine.modules.tools.msmsspectramerge.MsMsSpectraMergeModule.getBestMergedSpectrum(MsMsSpectraMergeModule.java:160)
        at io.github.mzmine.modules.io.gnpsexport.fbmn.GnpsFbmnMgfExportTask.export(GnpsFbmnMgfExportTask.java:282)
        at io.github.mzmine.modules.io.gnpsexport.fbmn.GnpsFbmnMgfExportTask.run(GnpsFbmnMgfExportTask.java:161)
        at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:60)
[14:28:05|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Processing of task Exporting files GNPS feature based molecular networking job done, status CANCELED

 I hope someone can help me.

**Comment by robinschmid** [comment]
Hey,
During the mass detection step - did you apply a scan filter? (the dialog where you can choose MS level=1, retention time range, scan range, ...) 
Maybe do mass detection again, but before clear these filters and only use the MS level as a filter. 

Does this solve the export issue?

**Comment by whank** [comment]
Hey robinschmid,

you are right, I filtered the retention time. When I removed the filters it worked. 

Thank you very much. :)

**Comment by robinschmid** [comment]
I know this issue ;)

**Comment by robinschmid** [comment]
I know this issue ;)
