### ISSUE TITLE
Batch Mode Not Working

### ISSUE THREAD

**Issue by chemichaelw** [mzmine/mzmine2#80]
I have been using the Beta v.2.15 for the last month consistently and am very happy with the improved batch mode that allows selections to be made as to which file each step to be used. I'm excited to see the new version 2.15 is finally out and hope that these improvements were incorporated. I have downloaded it and attempted use. However, I am unable to use any function (loading an old file, creating a new one, etc.) in the batch mode of this new release. Is this a general problem? Can you look into this? Is there some sort of java setting/version that is needed that wasn't before?

Thanks,
Mike

**Comment by dyrlund** [comment]
Hi Mike

I am using the batch mode daily and have no issues with it. An no, there are no java settings you need to set.

For us to help further, please describe your issue in more detail and provide the information listed under [**How to report issues**] (http://mzmine.github.io/support.html#Issues) on the MZmine webpage.

Thanks,

Thomas

**Comment by dyrlund** [comment]
Hi Mike,
We haven't heard anything from you and will therefore close the issue. Please let us know if you are still experiencing issues with the batch mode.
/Thomas

**Comment by chemichaelw** [comment]
Please Re-Open. I have had a lot of other things to do, but this problem persists. Here are the requested details:

1. Mzmine 2.15
2. Windows 7 -64bit

3.
    --->java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

--->R --version
'R' is not recognized as an internal or external command,
operable program or batch file.

--->R -version
'R' is not recognized as an internal or external command,
operable program or batch file.

4. 
![mzmine2-15-batch-problem1](https://cloud.githubusercontent.com/assets/13753423/9333990/6e5b7824-459a-11e5-985f-433a8bf472e9.png)
![mzmine2-15-batch-problem2](https://cloud.githubusercontent.com/assets/13753423/9333989/6e5ab510-459a-11e5-967d-994bdb0a15bd.png)

5. Here is the log message from the mzmine console window:
ds.gapfilling.samerange.SameRangeGapFillerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.isotopes.deisotoper.IsotopeGrouperModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.isotopes.isotopeprediction.IsotopePatternCalculator
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.smoothing.SmoothingModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.deconvolution.DeconvolutionModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.shapemodeler.ShapeModelerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.peakextender.PeakExtenderModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethod
s.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.filtering.duplicatefilter.DuplicateFilterModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.filtering.rowsfilter.RowsFilterModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.normalization.rtnormalizer.RTNormalizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.normalization.linear.LinearNormalizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.normalization.standardcompound.StandardCompoundNormalizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.rtmzplots.cvplot.CVPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.rtmzplots.logratioplot.LogratioPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.PCAPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.CDAPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.SammonsPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.clustering.ClusteringModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.heatmaps.HeatMapModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.customdbsearch.CustomDBSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.formulaprediction.FormulaPredictionModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.fragmentsearch.FragmentSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.adductsearch.AdductSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.complexsearch.ComplexSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.onlinedbsearch.OnlineDBSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.glycerophospholipidsearch.GPLipidSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.camera.CameraSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.nist.NistMsSearchModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmetho
ds.identification.formulapredictionpeaklist.FormulaPredictionPeakListModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.tic.TICVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.spectra.SpectraVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.ida.IDAVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.twod.TwoDVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.threed.ThreeDVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.neutralloss.NeutralLossVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.peaklisttable.PeakListTableModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.peaklisttable.export.IsotopePatternExportModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.peaklisttable.export.MSMSExportModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.scatterplot.ScatterPlotVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.histogram.HistogramVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.infovisualizer.InfoVisualizerModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization
.intensityplot.IntensityPlotModule
[11:06:11|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrange
calculator.MzRangeCalculatorModule
[11:06:11|FINE|MZmineCore]: Initializing GUI
[11:06:12|INFO|MZmineCore]: Showing main window
[11:06:21|FINEST|MainMenu]: Setting parameters for module Batch mode
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at net.sf.mzmine.parameters.parametertypes.selectors.RawDataFilesParamet
er.cloneParameter(RawDataFilesParameter.java:83)
        at net.sf.mzmine.parameters.parametertypes.selectors.RawDataFilesParamet
er.cloneParameter(RawDataFilesParameter.java:35)
        at net.sf.mzmine.parameters.impl.SimpleParameterSet.cloneParameterSet(Si
mpleParameterSet.java:128)
        at net.sf.mzmine.modules.batchmode.BatchSetupComponent.actionPerformed(B
atchSetupComponent.java:220)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at net.sf.mzmine.parameters.impl.SimpleParameterSet.showSetupDialog(Simp
leParameterSet.java:162)
        at net.sf.mzmine.desktop.impl.MainMenu.actionPerformed(MainMenu.java:354
)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown
Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
[11:07:44|FINEST|MainMenu]: Setting parameters for module Batch mode
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at net.sf.mzmine.parameters.parametertypes.selectors.RawDataFilesParamet
er.cloneParameter(RawDataFilesParameter.java:83)
        at net.sf.mzmine.parameters.parametertypes.selectors.RawDataFilesParamet
er.cloneParameter(RawDataFilesParameter.java:35)
        at net.sf.mzmine.parameters.impl.SimpleParameterSet.cloneParameterSet(Si
mpleParameterSet.java:128)
        at net.sf.mzmine.modules.batchmode.BatchSetupComponent.actionPerformed(B
atchSetupComponent.java:220)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at net.sf.mzmine.parameters.impl.SimpleParameterSet.showSetupDialog(Simp
leParameterSet.java:162)
        at net.sf.mzmine.desktop.impl.MainMenu.actionPerformed(MainMenu.java:354
)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown
Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)


6. We are unable to even create batch mode processes. It will not allow us to add modules to the batch. This is illustrated by the attached screen shots. Interestingly, once we have used a process outside of batch mode we are then able to place it into a batch, but not until we have used that specific module outside of batch mode. Old batch mode files do not load, either.

Thanks!

**Comment by dyrlund** [comment]
The issue seems to be related to the config/config.xml file missing in the MZmine directory. As a workaround, please try the following:
1. Start MZmine 2.15
2. When the GUI has loaded then exit MZmine (Project -> Exit)
3. Verify that you now have the conf/config.xml file in the MZmine directory
4. You should now be able to use the batch mode

/Thomas

![folder](https://cloud.githubusercontent.com/assets/10582167/9354103/dbf26072-466d-11e5-85c3-a7f4ef87ee29.png)

**Comment by tomas-pluskal** [comment]
I just submitted a pull request #83 that takes care of this exception.

Mike, please let us know if the solution suggested by Thomas worked or not.

**Comment by chemichaelw** [comment]
That's great! 
This solution did work. I am now able to run batch mode and it works very well! Thanks for the help!
