### ISSUE TITLE
ThermoRawDump.exe issue: not working on Ubuntu 18.04LTS (VirtualBox VM)

### ISSUE THREAD

**Issue by pamodeo-icb** [mzmine/mzmine2#817]
_### Basic information_
I have tried to load a series of raw files that are correctly processed by MZmine under Windows 10 Home in a MZmine installation in Ubuntu 18.04LTS (running in a VirtualBox VM installed on the same Windows 10 PC) and the loading fails (in both batch and interactive mode) with a "**No scans found**" exception (see below for details and output). 
The problem can be traced to ThermoRawDump.exe. In spite of several strategies to install and manage dependencies, I was unable to make it work (see details below).

_* My operating systems:_
Windows 10 Home version 1903 OS Build 18362.720 (64-bit)
Ubuntu 18.04 LTS (upgraded 2020/04/08) (64-bit)

_* My MZmine version:_ 
2.53 on both OS

_### What happened_
Error and normal behavior have been described above.
Below I report the MZmine screen output after raw file loading (Ubuntu), and the errors issued by ThermoRawDump.exe in one of the tested sw configuration.

**--------------------------- Ubuntu 18.04 LTS (upgraded 2020/04/08) -----------------------------**
**---------------------------      on VirtualBox 6.1.4 r136177 (Qt5.6.2)    -----------------------------**
_[9:14:06|FINEST|io.github.mzmine.gui.impl.MainMenu]: Setting parameters for module Raw data import
Gtk-Message: 09:14:07.192: GtkDialog mapped without a transient parent. This is discouraged.
[9:14:46|FINEST|io.github.mzmine.gui.impl.MainMenu]: Starting module Raw data import with parameters Raw data file names: [/home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw]
**[9:14:46|FINEST|io.github.mzmine.modules.io.rawdataimport.RawDataImportModule]: File /home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw type detected as THERMO_RAW
[9:14:46|FINEST|io.github.mzmine.taskcontrol.impl.TaskQueue]: Adding task "Opening file /home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw" to the task controller queue
[9:14:46|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Opening file /home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw
[9:14:46|INFO|io.github.mzmine.modules.io.rawdataimport.fileformats.NativeFileReadTask]: Opening file /home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw
java.lang.Exception: No scans found
	at io.github.mzmine.modules.io.rawdataimport.fileformats.NativeFileReadTask.run(NativeFileReadTask.java:149)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:60)
[9:14:47|SEVERE|io.github.mzmine.taskcontrol.impl.WorkerThread]: Error of task Opening file /home/sw/MA_test/WORKFLOW/DATA/file_14marzo18_raw/C_5_3_R1.raw: java.lang.Exception: No scans found (NativeFileReadTask.java:149)**
[9:15:02|INFO|io.github.mzmine.gui.impl.MainWindow]: Exiting MZmine_
---------------------------------------------------------------------------------------------------------

**Several wine and environment configurations were tried, but all ended with some sort of error and/or "file not found messages".**
As an example, after installing the current stable wine/winehq version (Windows Mono version 4.9.4) and the Microsoft Visual C++ 2008 Redistributable package (in a 32-bit wine environment) via winetricks, I got the following error message when trying to convert a raw file (using wine in a 32-bit mode/environment):

_WINEARCH=win32  WINEPREFIX=$HOME/wine32 wine ThermoRawDump.exe ../../C_5_3_R1.raw 
0009:fixme:ole:get_inproc_class_object unrecognised threading model 0 for object {1d23188d-53fe-4c25-b032-dc70acdbdc02}, should be main-threaded?
002e:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
002e:fixme:nls:SetProcessPreferredUILanguages 0, (nil), 0x649ee04
002e:fixme:nls:SetProcessPreferredUILanguages 4, 0x649ef24, 0x649ee04
002e:fixme:ole:type_memsize unhandled type 31
002e:fixme:ole:type_memsize unhandled type 31
002e:fixme:ole:get_param_info unhandled type 31
002e:fixme:ole:write_type_tfs unhandled type 31
002e:err:ole:dispatch_typelib_ps_CreateStub Failed to create proxy, hr 0x80004001.
002e:err:ole:dispatch_typelib_ps_CreateStub Failed to create proxy, hr 0x80004001.
002e:err:ole:marshal_object Failed to create an IRpcStubBuffer from IPSFactory for {e7cf6760-11cd-4260-b5b0-fce2ad97547b} with error 0x80004001
0009:err:ole:ClientIdentity_QueryMultipleInterfaces IRemUnknown_RemQueryInterface failed with error 0x80004002
ERROR: System.InvalidCastException: Specified cast is not valid.
  at ThermoRawDump.ThermoRawDump.Main (System.String[] args) [0x00056] in <473addaeab6c474899db820e84087d62>:0_ 

The same and/or other errors were issued when installing different Windows Mono environments.
The files used were, as mentioned above, flawlessly read under Windows.

**The problem is worsened by the fact that no other sw based on Thermo Windows libraries works on my Ubuntu installation**. Only **ThermoRawFileParser**, a file parser running on Linux with native mono implementation, which is a wrapper around .net (C#) ThermoFisher ThermoRawFileReader library, **reads and converts Thermo raw files into (indexed or non-indexed) mzML files**. However, while these latter are read and processed in MZmine, there are **discrepancies in the results they provide from those obtained with the original raw files**. I am currently investigating such differences and I will report about them as soon as I have some (even partly) conclusive results.

Incidentally, (but also this issue will be the subject of another report after further tests) when loading and **saving in MZmine** (interactively, under Windows 10) both an original raw file and the corresponding mzML file produced by ThermoRawFileParser, **in mzML format, I obtained files formed by one single, unformatted (i.e. no tabs/spaces between tags) , unterminated, huge record**.

Since the number of variables in the configuration of the OS and MZmine/file converters dependencies is huge, any suggestion about significant detail to test or report is welcome.
Also the raw/mzML files are available if required, although I fear that at present the problems are indeed more "basical".

**Comment by tomas-pluskal** [comment]
Hi @pamodeo-icb,
Actually the ThermoRawDump.exe is not supposed to work on non-Windows platforms. The wine approach is theoretically possible, but in practice quite tricky.
Regarding the other problems that you report (discrepancies in the results, mzML formatting), please file a separate issue for each problem, so we can keep things organized.

**Comment by pamodeo-icb** [comment]
Hi @tomas-pluskal ,
I am perfectly aware that, apart from the missing formatting in mzML export file, the other two issues in my previous post are not technically "MZmine issues". And that, as anticipated in my post, the mzML file formatting and ThermoRawFileParser problems need separate issues. Indeed, I just anticipated them, only because they are somewhat related to the main one and a possible rapid workaround on either of them would have considerably simplified both the exploration of this latter and the identification of possible workarounds and alternative solutions. Nonetheless, before posting new issues I prefer to be able to provide more details and perform a more accurate preliminary testing. I hope to be able to file today at least the one on mzML export. For the ThermoRawFileParser I will presumably file an issue on developer's site, but I still need to go through their paper and some additional testing. Meanwhile, I produced a msconvert mzML file for testing (produced with the 64-bit Windows version, since both the 32-bit Windows and any combination of version, Wine and .NET configuration under Linux did not work or produce non-functional files).

However, the problem of directly importing Thermo raw file (albeit with an external tool) surely affects MZmine user-friendliness and, combined with problems in conversion with other external tools, can heavily impact its overall usability in Linux-based workflows.
In this view, albeit tricky, the wine approach would be really useful. Since I am trying to make my full workflow working on Ubuntu installations based on LTS versions and "as vanilla as possible", just requiring the installation of my own DB and MS-related packages over a standard installation, finding a working solution could be of more general help for users working in a Linux environment. Thus, if you have any suggestion or trick, I am available for testing, especially in this "Covid-19 lockdown" period, since I have more spare time for this kind of systematic trial activity.

**Comment by pamodeo-icb** [comment]
While I wasn't able to make ThermoRawDump.exe working under Linux, I now can convert Thermo raw spectra in both profile and centroid mode into mzML with both msconvert and ThermoRawFileParser on my Ubuntu 18.04LTS virtual machine.
Since the installation/configuration of the two programs resulted very sensitive to the exact procedures, I am going to report them under a separate issue.
Obviously, any suggestion about a working ThermoRawDump.exe setup under Linux is still welcome.
