### ISSUE TITLE
error Could not initialize GUI

### ISSUE THREAD

**Issue by LanyingMa** [mzmine/mzmine2#896]
### Basic information

* My operating system: Ubuntu 18.04 64 bit
* My MZmine version: 2.53

### What happened

* i tried to initiate MZmine on aws ec2 instance with ubuntu 18.04 64 bit . but when i  `bash startMZmine-Linux`, it got the error 
```
[22:45:49|SEVERE|io.github.mzmine.main.MZmineCore]: Could not initialize GUI(java.lang.reflect.InvocationTargetException@java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367))
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:169)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:197)
	at java.desktop/java.awt.Window.<init>(Window.java:538)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at io.github.mzmine.gui.impl.MainWindow.<init>(MainWindow.java:69)
	at io.github.mzmine.main.MZmineCore$1.run(MZmineCore.java:145)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.
```
my Java version is ```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```
thank you

**Comment by tomas-pluskal** [comment]
If you're running MZmine in the batch mode (without GUI), you need to specify the path to the batch file as a parameter.
E.g., 

`bash startMZmine-Linux /tmp/path/to/batch.xml`

**Comment by LanyingMa** [comment]
thank you for your reply.. i did not run it in Bach mode yet ( i will try it later); i actually run it in EC2 instance with systems as Ubuntu 18.04.    Could we run MZmine in ec2 instance?
