### ISSUE TITLE
Java error when i try to import Waters raw files

### ISSUE THREAD

**Issue by amrsalem** [mzmine/mzmine2#94]
I tried with mzML and the import works but when I try to use the Water raw file it gives me an error.  I am using the new version of mzmine 2.15 but I also tried this on 2.14.2 and it still doesn't work.  I tried this on a PC and it imported the waters raw file fine but I want to use my mac because it has much more power.  Any help is highly appreciated. Below is the information you requested.  

I am using 64bit OSX 10.9.5

 java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
 R --version
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

the console log:
Checking physical memory size...
Found 8192 MB memory
Java heap size set to 6144 MB
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

[17:47:49|INFO|MZmineCore]: Starting MZmine 2.15
[17:47:49|FINE|TmpFileCleanup]: Checking for old temporary files...
[17:47:49|FINE|MZmineCore]: Loading core classes..
[17:47:49|FINE|MZmineCore]: Initializing core classes..
[17:47:49|FINE|MZmineCore]: Loading modules
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectload.ProjectLoadModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectsave.ProjectSaveAsModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.projectmethods.projectclose.ProjectCloseModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.batchmode.BatchModeModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.shoulderpeaksfilter.ShoulderPeaksFilterModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.ChromatogramBuilderModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.gridmass.GridMassModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.manual.ManualPeakPickerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.msms.MsMsPeakPickerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scanfilters.ScanFiltersModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.cropper.CropFilterModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.baselinecorrection.BaselineCorrectionModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.alignscans.AlignScansModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.filtering.scansmoothing.ScanSmoothingModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.orderdatafiles.OrderDataFilesModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.orderpeaklists.OrderPeakListsModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.join.JoinAlignerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.alignment.ransac.RansacAlignerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.csvexport.CSVExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.metaboanalystexport.MetaboAnalystExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabexport.MzTabExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.sqlexport.SQLExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlexport.XMLExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.casmiimport.CasmiImportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.mztabimport.MzTabImportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.io.xmlimport.XMLImportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.gapfilling.samerange.SameRangeGapFillerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.deisotoper.IsotopeGrouperModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.isotopes.isotopeprediction.IsotopePatternCalculator
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.smoothing.SmoothingModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.shapemodeler.ShapeModelerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.peakpicking.peakextender.PeakExtenderModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.rawdatamethods.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.duplicatefilter.DuplicateFilterModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.filtering.rowsfilter.RowsFilterModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.rtnormalizer.RTNormalizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.linear.LinearNormalizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.normalization.standardcompound.StandardCompoundNormalizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.cvplot.CVPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.rtmzplots.logratioplot.LogratioPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.PCAPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.CDAPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.projectionplots.SammonsPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.clustering.ClusteringModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.dataanalysis.heatmaps.HeatMapModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.customdbsearch.CustomDBSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulaprediction.FormulaPredictionModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.fragmentsearch.FragmentSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.adductsearch.AdductSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.complexsearch.ComplexSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.OnlineDBSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.glycerophospholipidsearch.GPLipidSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.camera.CameraSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.nist.NistMsSearchModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.peaklistmethods.identification.formulapredictionpeaklist.FormulaPredictionPeakListModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.tic.TICVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.spectra.SpectraVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.ida.IDAVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.twod.TwoDVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.threed.ThreeDVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.neutralloss.NeutralLossVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.PeakListTableModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.IsotopePatternExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.peaklisttable.export.MSMSExportModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.scatterplot.ScatterPlotVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.histogram.HistogramVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.infovisualizer.InfoVisualizerModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.visualization.intensityplot.IntensityPlotModule
[17:47:49|FINEST|MZmineCore]: Loading module net.sf.mzmine.modules.tools.mzrangecalculator.MzRangeCalculatorModule
[17:47:50|FINE|MZmineCore]: Initializing GUI
[17:47:51|FINEST|MZmineConfigurationImpl]: Loading desktop configuration
[17:47:51|FINEST|MZmineConfigurationImpl]: Loading modules configuration
[17:47:51|INFO|MZmineConfigurationImpl]: Loaded configuration from file conf/config.xml
[17:47:51|INFO|MZmineCore]: Showing main window
[17:47:55|FINEST|MainMenu]: Setting parameters for module Raw data import
[17:47:57|FINEST|MainMenu]: Starting module Raw data import with parameters Raw data file names: [/Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw]
[17:47:57|FINEST|RawDataImportModule]: File /Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw type detected as WATERS_RAW
[17:47:57|FINEST|TaskQueue]: Adding task "Opening file /Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw" to the task controller queue
[17:47:57|INFO|WorkerThread]: Starting processing of task Opening file /Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw
[17:47:57|INFO|NativeFileReadTask]: Opening file /Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw
java.io.IOException: Cannot run program "wine": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at net.sf.mzmine.modules.rawdatamethods.rawdataimport.fileformats.NativeFileReadTask.run(NativeFileReadTask.java:131)
	at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
[17:47:57|SEVERE|WorkerThread]: Error of task Opening file /Users/aali/Desktop/Lipid Experiments Mac/150815 Sample Prep & LC Trial 1/Mass Spec/Blank1.raw: java.io.IOException: Cannot run program "wine": error=2, No such file or directory (ProcessBuilder.java:1048)

![java error 1](https://cloud.githubusercontent.com/assets/3181706/9425992/5a7048c2-48f5-11e5-84cc-14954dd24ecf.jpg)

**Comment by tomas-pluskal** [comment]
Hi.
The import of Waters/Thermo files works only on Windows, because it requires native libraries from the vendors. See the MZmine manual.
Tomas

**Comment by amrsalem** [comment]
Thank you for your help.  I appreciate it.

**Comment by MrDarkHorse** [comment]
Running into this same issue.  Why would it even be looking for wine if that's not an option.  Isn't the point of wine to run Windows stuff in a UNIX environment?

**Comment by tomas-pluskal** [comment]
Wine is an option. It is just difficult to make it work, so we don't officially recommend it. 

Try it and let me know if you succeeded.

**Comment by caot** [comment]
Did you solved the issues?
