### ISSUE TITLE
Password error in batch jobs

### ISSUE THREAD

**Issue by GulfamMuhammad** [mzmine/mzmine2#943]
### Basic information

* My operating system: Windows
* My MZmine version: MZmine-2.53-Windows

### What happened

When I use mzmine manually and try to process data including the form to submit GNPS job, it only produces the mgf and csv output and doesn't submit the job.
When I am trying to run it through batch job it is not even producing the output files (.mgf and .csv).
It gave an error : "_[11:20:20|WARNING|io.github.mzmine.main.MZmineCore]: Error while loading parameter values for Password(java.lang.IllegalArgumentException: Illegal base64 character 40@java.base/java.util.Base64$Decoder.decode0(Base64.java:743))"_

It also generated an exception : 
_"Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode)
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: log\mzmine.log.lck
java.nio.file.NoSuchFileException: log\mzmine.log.lck
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
        at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:511)
        at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:278)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
        at java.base/java.lang.Class.newInstance(Class.java:590)
        at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
        at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
        at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
        at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
        at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
        at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
        at java.logging/java.util.logging.Logger.log(Logger.java:976)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
        at java.logging/java.util.logging.Logger.log(Logger.java:1029)
        at java.logging/java.util.logging.Logger.info(Logger.java:1802)
        at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:81)"_

In the batch mode I also tried to enter the encrypted password that I got by saving the configuration file with normal password. but it didn't work and give me following error:
_[11:14:33|FINEST|io.github.mzmine.main.MZmineCore]: Loading module io.github.mzmine.modules.visualization.spectra.simplespectra.datapointprocessing.isotopes.deisotoper.DPPIsotopeGrouperModule
**[11:14:33|INFO|io.github.mzmine.modules.batchmode.BatchModeModule]: Running batch from file mzminepar_new.xml
io.github.mzmine.util.exceptions.DecryptionException: Could not Decrypt String!
        at io.github.mzmine.util.StringCrypter.decrypt(StringCrypter.java:126)
        at io.github.mzmine.parameters.parametertypes.PasswordParameter.loadValueFromXML(PasswordParameter.java:109)
        at io.github.mzmine.parameters.impl.SimpleParameterSet.loadValuesFromXML(SimpleParameterSet.java:81)
        at io.github.mzmine.parameters.parametertypes.submodules.OptionalModuleParameter.loadValueFromXML(OptionalModuleParameter.java:123)
        at io.github.mzmine.parameters.impl.SimpleParameterSet.loadValuesFromXML(SimpleParameterSet.java:81)
        at io.github.mzmine.modules.batchmode.BatchQueue.loadFromXml(BatchQueue.java:110)
        at io.github.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:93)
        at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:259)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        at java.base/com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
        at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
        at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
        at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2208)
        at io.github.mzmine.util.StringCrypter.decrypt(StringCrypter.java:121)
        ... 7 more_**

**Comment by GulfamMuhammad** [comment]
I changed my GNPS password to a 16 letters password, all alphabets. It gave me following error while loading the parameter file:

[16:52:02|INFO|io.github.mzmine.modules.batchmode.BatchModeModule]: Running batch from file mzminepar_new.xml
io.github.mzmine.util.exceptions.DecryptionException: Could not Decrypt String!
        at io.github.mzmine.util.StringCrypter.decrypt(StringCrypter.java:126)
        at io.github.mzmine.parameters.parametertypes.PasswordParameter.loadValueFromXML(PasswordParameter.java:109)
        at io.github.mzmine.parameters.impl.SimpleParameterSet.loadValuesFromXML(SimpleParameterSet.java:81)
        at io.github.mzmine.parameters.parametertypes.submodules.OptionalModuleParameter.loadValueFromXML(OptionalModuleParameter.java:123)
        at io.github.mzmine.parameters.impl.SimpleParameterSet.loadValuesFromXML(SimpleParameterSet.java:81)
        at io.github.mzmine.modules.batchmode.BatchQueue.loadFromXml(BatchQueue.java:110)
        at io.github.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:93)
        at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:259)
Caused by: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
        at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1005)
        at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
        at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2208)
        at io.github.mzmine.util.StringCrypter.decrypt(StringCrypter.java:121)
        ... 7 more

**Comment by GulfamMuhammad** [comment]
So far, I have tried changing my password on GNPS. This time I used a 9 character password with all alphabets, lower case.
I got following error:
**Error while loading parameter values for Password(java.lang.IllegalArgumentException: Last unit does not have enough valid bits@java.base/java.util.Base64$Decoder.decode0(Base64.java:763))**

Note: I am using batch mode by passing parameters to .bat file.
